
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FavoriteMenu` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FavoriteMenu
 * 
 */
export type FavoriteMenuModel = runtime.Types.Result.DefaultSelection<Prisma.$FavoriteMenuPayload>

export type AggregateFavoriteMenu = {
  _count: FavoriteMenuCountAggregateOutputType | null
  _min: FavoriteMenuMinAggregateOutputType | null
  _max: FavoriteMenuMaxAggregateOutputType | null
}

export type FavoriteMenuMinAggregateOutputType = {
  id: string | null
  pembeliId: string | null
  menuId: string | null
  createdAt: Date | null
}

export type FavoriteMenuMaxAggregateOutputType = {
  id: string | null
  pembeliId: string | null
  menuId: string | null
  createdAt: Date | null
}

export type FavoriteMenuCountAggregateOutputType = {
  id: number
  pembeliId: number
  menuId: number
  createdAt: number
  _all: number
}


export type FavoriteMenuMinAggregateInputType = {
  id?: true
  pembeliId?: true
  menuId?: true
  createdAt?: true
}

export type FavoriteMenuMaxAggregateInputType = {
  id?: true
  pembeliId?: true
  menuId?: true
  createdAt?: true
}

export type FavoriteMenuCountAggregateInputType = {
  id?: true
  pembeliId?: true
  menuId?: true
  createdAt?: true
  _all?: true
}

export type FavoriteMenuAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FavoriteMenu to aggregate.
   */
  where?: Prisma.FavoriteMenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteMenus to fetch.
   */
  orderBy?: Prisma.FavoriteMenuOrderByWithRelationInput | Prisma.FavoriteMenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FavoriteMenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteMenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteMenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FavoriteMenus
  **/
  _count?: true | FavoriteMenuCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FavoriteMenuMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FavoriteMenuMaxAggregateInputType
}

export type GetFavoriteMenuAggregateType<T extends FavoriteMenuAggregateArgs> = {
      [P in keyof T & keyof AggregateFavoriteMenu]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFavoriteMenu[P]>
    : Prisma.GetScalarType<T[P], AggregateFavoriteMenu[P]>
}




export type FavoriteMenuGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteMenuWhereInput
  orderBy?: Prisma.FavoriteMenuOrderByWithAggregationInput | Prisma.FavoriteMenuOrderByWithAggregationInput[]
  by: Prisma.FavoriteMenuScalarFieldEnum[] | Prisma.FavoriteMenuScalarFieldEnum
  having?: Prisma.FavoriteMenuScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FavoriteMenuCountAggregateInputType | true
  _min?: FavoriteMenuMinAggregateInputType
  _max?: FavoriteMenuMaxAggregateInputType
}

export type FavoriteMenuGroupByOutputType = {
  id: string
  pembeliId: string
  menuId: string
  createdAt: Date
  _count: FavoriteMenuCountAggregateOutputType | null
  _min: FavoriteMenuMinAggregateOutputType | null
  _max: FavoriteMenuMaxAggregateOutputType | null
}

export type GetFavoriteMenuGroupByPayload<T extends FavoriteMenuGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FavoriteMenuGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FavoriteMenuGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FavoriteMenuGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FavoriteMenuGroupByOutputType[P]>
      }
    >
  >



export type FavoriteMenuWhereInput = {
  AND?: Prisma.FavoriteMenuWhereInput | Prisma.FavoriteMenuWhereInput[]
  OR?: Prisma.FavoriteMenuWhereInput[]
  NOT?: Prisma.FavoriteMenuWhereInput | Prisma.FavoriteMenuWhereInput[]
  id?: Prisma.StringFilter<"FavoriteMenu"> | string
  pembeliId?: Prisma.StringFilter<"FavoriteMenu"> | string
  menuId?: Prisma.StringFilter<"FavoriteMenu"> | string
  createdAt?: Prisma.DateTimeFilter<"FavoriteMenu"> | Date | string
  pembeli?: Prisma.XOR<Prisma.PembeliScalarRelationFilter, Prisma.PembeliWhereInput>
  menu?: Prisma.XOR<Prisma.MenuScalarRelationFilter, Prisma.MenuWhereInput>
}

export type FavoriteMenuOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pembeliId?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  pembeli?: Prisma.PembeliOrderByWithRelationInput
  menu?: Prisma.MenuOrderByWithRelationInput
  _relevance?: Prisma.FavoriteMenuOrderByRelevanceInput
}

export type FavoriteMenuWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  pembeliId_menuId?: Prisma.FavoriteMenuPembeliIdMenuIdCompoundUniqueInput
  AND?: Prisma.FavoriteMenuWhereInput | Prisma.FavoriteMenuWhereInput[]
  OR?: Prisma.FavoriteMenuWhereInput[]
  NOT?: Prisma.FavoriteMenuWhereInput | Prisma.FavoriteMenuWhereInput[]
  pembeliId?: Prisma.StringFilter<"FavoriteMenu"> | string
  menuId?: Prisma.StringFilter<"FavoriteMenu"> | string
  createdAt?: Prisma.DateTimeFilter<"FavoriteMenu"> | Date | string
  pembeli?: Prisma.XOR<Prisma.PembeliScalarRelationFilter, Prisma.PembeliWhereInput>
  menu?: Prisma.XOR<Prisma.MenuScalarRelationFilter, Prisma.MenuWhereInput>
}, "id" | "pembeliId_menuId">

export type FavoriteMenuOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pembeliId?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FavoriteMenuCountOrderByAggregateInput
  _max?: Prisma.FavoriteMenuMaxOrderByAggregateInput
  _min?: Prisma.FavoriteMenuMinOrderByAggregateInput
}

export type FavoriteMenuScalarWhereWithAggregatesInput = {
  AND?: Prisma.FavoriteMenuScalarWhereWithAggregatesInput | Prisma.FavoriteMenuScalarWhereWithAggregatesInput[]
  OR?: Prisma.FavoriteMenuScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FavoriteMenuScalarWhereWithAggregatesInput | Prisma.FavoriteMenuScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FavoriteMenu"> | string
  pembeliId?: Prisma.StringWithAggregatesFilter<"FavoriteMenu"> | string
  menuId?: Prisma.StringWithAggregatesFilter<"FavoriteMenu"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FavoriteMenu"> | Date | string
}

export type FavoriteMenuCreateInput = {
  id?: string
  createdAt?: Date | string
  pembeli: Prisma.PembeliCreateNestedOneWithoutFavoriteMenusInput
  menu: Prisma.MenuCreateNestedOneWithoutFavoritesInput
}

export type FavoriteMenuUncheckedCreateInput = {
  id?: string
  pembeliId: string
  menuId: string
  createdAt?: Date | string
}

export type FavoriteMenuUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pembeli?: Prisma.PembeliUpdateOneRequiredWithoutFavoriteMenusNestedInput
  menu?: Prisma.MenuUpdateOneRequiredWithoutFavoritesNestedInput
}

export type FavoriteMenuUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pembeliId?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteMenuCreateManyInput = {
  id?: string
  pembeliId: string
  menuId: string
  createdAt?: Date | string
}

export type FavoriteMenuUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteMenuUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pembeliId?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteMenuListRelationFilter = {
  every?: Prisma.FavoriteMenuWhereInput
  some?: Prisma.FavoriteMenuWhereInput
  none?: Prisma.FavoriteMenuWhereInput
}

export type FavoriteMenuOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FavoriteMenuOrderByRelevanceInput = {
  fields: Prisma.FavoriteMenuOrderByRelevanceFieldEnum | Prisma.FavoriteMenuOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FavoriteMenuPembeliIdMenuIdCompoundUniqueInput = {
  pembeliId: string
  menuId: string
}

export type FavoriteMenuCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pembeliId?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FavoriteMenuMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pembeliId?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FavoriteMenuMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pembeliId?: Prisma.SortOrder
  menuId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FavoriteMenuCreateNestedManyWithoutPembeliInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput> | Prisma.FavoriteMenuCreateWithoutPembeliInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput | Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput[]
  createMany?: Prisma.FavoriteMenuCreateManyPembeliInputEnvelope
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
}

export type FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput> | Prisma.FavoriteMenuCreateWithoutPembeliInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput | Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput[]
  createMany?: Prisma.FavoriteMenuCreateManyPembeliInputEnvelope
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
}

export type FavoriteMenuUpdateManyWithoutPembeliNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput> | Prisma.FavoriteMenuCreateWithoutPembeliInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput | Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput[]
  upsert?: Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutPembeliInput | Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutPembeliInput[]
  createMany?: Prisma.FavoriteMenuCreateManyPembeliInputEnvelope
  set?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  disconnect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  delete?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  update?: Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutPembeliInput | Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutPembeliInput[]
  updateMany?: Prisma.FavoriteMenuUpdateManyWithWhereWithoutPembeliInput | Prisma.FavoriteMenuUpdateManyWithWhereWithoutPembeliInput[]
  deleteMany?: Prisma.FavoriteMenuScalarWhereInput | Prisma.FavoriteMenuScalarWhereInput[]
}

export type FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput> | Prisma.FavoriteMenuCreateWithoutPembeliInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput | Prisma.FavoriteMenuCreateOrConnectWithoutPembeliInput[]
  upsert?: Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutPembeliInput | Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutPembeliInput[]
  createMany?: Prisma.FavoriteMenuCreateManyPembeliInputEnvelope
  set?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  disconnect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  delete?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  update?: Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutPembeliInput | Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutPembeliInput[]
  updateMany?: Prisma.FavoriteMenuUpdateManyWithWhereWithoutPembeliInput | Prisma.FavoriteMenuUpdateManyWithWhereWithoutPembeliInput[]
  deleteMany?: Prisma.FavoriteMenuScalarWhereInput | Prisma.FavoriteMenuScalarWhereInput[]
}

export type FavoriteMenuCreateNestedManyWithoutMenuInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutMenuInput, Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput> | Prisma.FavoriteMenuCreateWithoutMenuInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput | Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput[]
  createMany?: Prisma.FavoriteMenuCreateManyMenuInputEnvelope
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
}

export type FavoriteMenuUncheckedCreateNestedManyWithoutMenuInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutMenuInput, Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput> | Prisma.FavoriteMenuCreateWithoutMenuInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput | Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput[]
  createMany?: Prisma.FavoriteMenuCreateManyMenuInputEnvelope
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
}

export type FavoriteMenuUpdateManyWithoutMenuNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutMenuInput, Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput> | Prisma.FavoriteMenuCreateWithoutMenuInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput | Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput[]
  upsert?: Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutMenuInput | Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutMenuInput[]
  createMany?: Prisma.FavoriteMenuCreateManyMenuInputEnvelope
  set?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  disconnect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  delete?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  update?: Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutMenuInput | Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutMenuInput[]
  updateMany?: Prisma.FavoriteMenuUpdateManyWithWhereWithoutMenuInput | Prisma.FavoriteMenuUpdateManyWithWhereWithoutMenuInput[]
  deleteMany?: Prisma.FavoriteMenuScalarWhereInput | Prisma.FavoriteMenuScalarWhereInput[]
}

export type FavoriteMenuUncheckedUpdateManyWithoutMenuNestedInput = {
  create?: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutMenuInput, Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput> | Prisma.FavoriteMenuCreateWithoutMenuInput[] | Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput[]
  connectOrCreate?: Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput | Prisma.FavoriteMenuCreateOrConnectWithoutMenuInput[]
  upsert?: Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutMenuInput | Prisma.FavoriteMenuUpsertWithWhereUniqueWithoutMenuInput[]
  createMany?: Prisma.FavoriteMenuCreateManyMenuInputEnvelope
  set?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  disconnect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  delete?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  connect?: Prisma.FavoriteMenuWhereUniqueInput | Prisma.FavoriteMenuWhereUniqueInput[]
  update?: Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutMenuInput | Prisma.FavoriteMenuUpdateWithWhereUniqueWithoutMenuInput[]
  updateMany?: Prisma.FavoriteMenuUpdateManyWithWhereWithoutMenuInput | Prisma.FavoriteMenuUpdateManyWithWhereWithoutMenuInput[]
  deleteMany?: Prisma.FavoriteMenuScalarWhereInput | Prisma.FavoriteMenuScalarWhereInput[]
}

export type FavoriteMenuCreateWithoutPembeliInput = {
  id?: string
  createdAt?: Date | string
  menu: Prisma.MenuCreateNestedOneWithoutFavoritesInput
}

export type FavoriteMenuUncheckedCreateWithoutPembeliInput = {
  id?: string
  menuId: string
  createdAt?: Date | string
}

export type FavoriteMenuCreateOrConnectWithoutPembeliInput = {
  where: Prisma.FavoriteMenuWhereUniqueInput
  create: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput>
}

export type FavoriteMenuCreateManyPembeliInputEnvelope = {
  data: Prisma.FavoriteMenuCreateManyPembeliInput | Prisma.FavoriteMenuCreateManyPembeliInput[]
  skipDuplicates?: boolean
}

export type FavoriteMenuUpsertWithWhereUniqueWithoutPembeliInput = {
  where: Prisma.FavoriteMenuWhereUniqueInput
  update: Prisma.XOR<Prisma.FavoriteMenuUpdateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedUpdateWithoutPembeliInput>
  create: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedCreateWithoutPembeliInput>
}

export type FavoriteMenuUpdateWithWhereUniqueWithoutPembeliInput = {
  where: Prisma.FavoriteMenuWhereUniqueInput
  data: Prisma.XOR<Prisma.FavoriteMenuUpdateWithoutPembeliInput, Prisma.FavoriteMenuUncheckedUpdateWithoutPembeliInput>
}

export type FavoriteMenuUpdateManyWithWhereWithoutPembeliInput = {
  where: Prisma.FavoriteMenuScalarWhereInput
  data: Prisma.XOR<Prisma.FavoriteMenuUpdateManyMutationInput, Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliInput>
}

export type FavoriteMenuScalarWhereInput = {
  AND?: Prisma.FavoriteMenuScalarWhereInput | Prisma.FavoriteMenuScalarWhereInput[]
  OR?: Prisma.FavoriteMenuScalarWhereInput[]
  NOT?: Prisma.FavoriteMenuScalarWhereInput | Prisma.FavoriteMenuScalarWhereInput[]
  id?: Prisma.StringFilter<"FavoriteMenu"> | string
  pembeliId?: Prisma.StringFilter<"FavoriteMenu"> | string
  menuId?: Prisma.StringFilter<"FavoriteMenu"> | string
  createdAt?: Prisma.DateTimeFilter<"FavoriteMenu"> | Date | string
}

export type FavoriteMenuCreateWithoutMenuInput = {
  id?: string
  createdAt?: Date | string
  pembeli: Prisma.PembeliCreateNestedOneWithoutFavoriteMenusInput
}

export type FavoriteMenuUncheckedCreateWithoutMenuInput = {
  id?: string
  pembeliId: string
  createdAt?: Date | string
}

export type FavoriteMenuCreateOrConnectWithoutMenuInput = {
  where: Prisma.FavoriteMenuWhereUniqueInput
  create: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutMenuInput, Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput>
}

export type FavoriteMenuCreateManyMenuInputEnvelope = {
  data: Prisma.FavoriteMenuCreateManyMenuInput | Prisma.FavoriteMenuCreateManyMenuInput[]
  skipDuplicates?: boolean
}

export type FavoriteMenuUpsertWithWhereUniqueWithoutMenuInput = {
  where: Prisma.FavoriteMenuWhereUniqueInput
  update: Prisma.XOR<Prisma.FavoriteMenuUpdateWithoutMenuInput, Prisma.FavoriteMenuUncheckedUpdateWithoutMenuInput>
  create: Prisma.XOR<Prisma.FavoriteMenuCreateWithoutMenuInput, Prisma.FavoriteMenuUncheckedCreateWithoutMenuInput>
}

export type FavoriteMenuUpdateWithWhereUniqueWithoutMenuInput = {
  where: Prisma.FavoriteMenuWhereUniqueInput
  data: Prisma.XOR<Prisma.FavoriteMenuUpdateWithoutMenuInput, Prisma.FavoriteMenuUncheckedUpdateWithoutMenuInput>
}

export type FavoriteMenuUpdateManyWithWhereWithoutMenuInput = {
  where: Prisma.FavoriteMenuScalarWhereInput
  data: Prisma.XOR<Prisma.FavoriteMenuUpdateManyMutationInput, Prisma.FavoriteMenuUncheckedUpdateManyWithoutMenuInput>
}

export type FavoriteMenuCreateManyPembeliInput = {
  id?: string
  menuId: string
  createdAt?: Date | string
}

export type FavoriteMenuUpdateWithoutPembeliInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menu?: Prisma.MenuUpdateOneRequiredWithoutFavoritesNestedInput
}

export type FavoriteMenuUncheckedUpdateWithoutPembeliInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteMenuUncheckedUpdateManyWithoutPembeliInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  menuId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteMenuCreateManyMenuInput = {
  id?: string
  pembeliId: string
  createdAt?: Date | string
}

export type FavoriteMenuUpdateWithoutMenuInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pembeli?: Prisma.PembeliUpdateOneRequiredWithoutFavoriteMenusNestedInput
}

export type FavoriteMenuUncheckedUpdateWithoutMenuInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pembeliId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FavoriteMenuUncheckedUpdateManyWithoutMenuInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pembeliId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FavoriteMenuSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pembeliId?: boolean
  menuId?: boolean
  createdAt?: boolean
  pembeli?: boolean | Prisma.PembeliDefaultArgs<ExtArgs>
  menu?: boolean | Prisma.MenuDefaultArgs<ExtArgs>
}, ExtArgs["result"]["favoriteMenu"]>



export type FavoriteMenuSelectScalar = {
  id?: boolean
  pembeliId?: boolean
  menuId?: boolean
  createdAt?: boolean
}

export type FavoriteMenuOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pembeliId" | "menuId" | "createdAt", ExtArgs["result"]["favoriteMenu"]>
export type FavoriteMenuInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  pembeli?: boolean | Prisma.PembeliDefaultArgs<ExtArgs>
  menu?: boolean | Prisma.MenuDefaultArgs<ExtArgs>
}

export type $FavoriteMenuPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FavoriteMenu"
  objects: {
    pembeli: Prisma.$PembeliPayload<ExtArgs>
    menu: Prisma.$MenuPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pembeliId: string
    menuId: string
    createdAt: Date
  }, ExtArgs["result"]["favoriteMenu"]>
  composites: {}
}

export type FavoriteMenuGetPayload<S extends boolean | null | undefined | FavoriteMenuDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload, S>

export type FavoriteMenuCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FavoriteMenuFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FavoriteMenuCountAggregateInputType | true
  }

export interface FavoriteMenuDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FavoriteMenu'], meta: { name: 'FavoriteMenu' } }
  /**
   * Find zero or one FavoriteMenu that matches the filter.
   * @param {FavoriteMenuFindUniqueArgs} args - Arguments to find a FavoriteMenu
   * @example
   * // Get one FavoriteMenu
   * const favoriteMenu = await prisma.favoriteMenu.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FavoriteMenuFindUniqueArgs>(args: Prisma.SelectSubset<T, FavoriteMenuFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FavoriteMenu that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FavoriteMenuFindUniqueOrThrowArgs} args - Arguments to find a FavoriteMenu
   * @example
   * // Get one FavoriteMenu
   * const favoriteMenu = await prisma.favoriteMenu.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FavoriteMenuFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FavoriteMenuFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FavoriteMenu that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuFindFirstArgs} args - Arguments to find a FavoriteMenu
   * @example
   * // Get one FavoriteMenu
   * const favoriteMenu = await prisma.favoriteMenu.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FavoriteMenuFindFirstArgs>(args?: Prisma.SelectSubset<T, FavoriteMenuFindFirstArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FavoriteMenu that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuFindFirstOrThrowArgs} args - Arguments to find a FavoriteMenu
   * @example
   * // Get one FavoriteMenu
   * const favoriteMenu = await prisma.favoriteMenu.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FavoriteMenuFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FavoriteMenuFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FavoriteMenus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FavoriteMenus
   * const favoriteMenus = await prisma.favoriteMenu.findMany()
   * 
   * // Get first 10 FavoriteMenus
   * const favoriteMenus = await prisma.favoriteMenu.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const favoriteMenuWithIdOnly = await prisma.favoriteMenu.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FavoriteMenuFindManyArgs>(args?: Prisma.SelectSubset<T, FavoriteMenuFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FavoriteMenu.
   * @param {FavoriteMenuCreateArgs} args - Arguments to create a FavoriteMenu.
   * @example
   * // Create one FavoriteMenu
   * const FavoriteMenu = await prisma.favoriteMenu.create({
   *   data: {
   *     // ... data to create a FavoriteMenu
   *   }
   * })
   * 
   */
  create<T extends FavoriteMenuCreateArgs>(args: Prisma.SelectSubset<T, FavoriteMenuCreateArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FavoriteMenus.
   * @param {FavoriteMenuCreateManyArgs} args - Arguments to create many FavoriteMenus.
   * @example
   * // Create many FavoriteMenus
   * const favoriteMenu = await prisma.favoriteMenu.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FavoriteMenuCreateManyArgs>(args?: Prisma.SelectSubset<T, FavoriteMenuCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FavoriteMenu.
   * @param {FavoriteMenuDeleteArgs} args - Arguments to delete one FavoriteMenu.
   * @example
   * // Delete one FavoriteMenu
   * const FavoriteMenu = await prisma.favoriteMenu.delete({
   *   where: {
   *     // ... filter to delete one FavoriteMenu
   *   }
   * })
   * 
   */
  delete<T extends FavoriteMenuDeleteArgs>(args: Prisma.SelectSubset<T, FavoriteMenuDeleteArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FavoriteMenu.
   * @param {FavoriteMenuUpdateArgs} args - Arguments to update one FavoriteMenu.
   * @example
   * // Update one FavoriteMenu
   * const favoriteMenu = await prisma.favoriteMenu.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FavoriteMenuUpdateArgs>(args: Prisma.SelectSubset<T, FavoriteMenuUpdateArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FavoriteMenus.
   * @param {FavoriteMenuDeleteManyArgs} args - Arguments to filter FavoriteMenus to delete.
   * @example
   * // Delete a few FavoriteMenus
   * const { count } = await prisma.favoriteMenu.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FavoriteMenuDeleteManyArgs>(args?: Prisma.SelectSubset<T, FavoriteMenuDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FavoriteMenus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FavoriteMenus
   * const favoriteMenu = await prisma.favoriteMenu.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FavoriteMenuUpdateManyArgs>(args: Prisma.SelectSubset<T, FavoriteMenuUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FavoriteMenu.
   * @param {FavoriteMenuUpsertArgs} args - Arguments to update or create a FavoriteMenu.
   * @example
   * // Update or create a FavoriteMenu
   * const favoriteMenu = await prisma.favoriteMenu.upsert({
   *   create: {
   *     // ... data to create a FavoriteMenu
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FavoriteMenu we want to update
   *   }
   * })
   */
  upsert<T extends FavoriteMenuUpsertArgs>(args: Prisma.SelectSubset<T, FavoriteMenuUpsertArgs<ExtArgs>>): Prisma.Prisma__FavoriteMenuClient<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FavoriteMenus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuCountArgs} args - Arguments to filter FavoriteMenus to count.
   * @example
   * // Count the number of FavoriteMenus
   * const count = await prisma.favoriteMenu.count({
   *   where: {
   *     // ... the filter for the FavoriteMenus we want to count
   *   }
   * })
  **/
  count<T extends FavoriteMenuCountArgs>(
    args?: Prisma.Subset<T, FavoriteMenuCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FavoriteMenuCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FavoriteMenu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FavoriteMenuAggregateArgs>(args: Prisma.Subset<T, FavoriteMenuAggregateArgs>): Prisma.PrismaPromise<GetFavoriteMenuAggregateType<T>>

  /**
   * Group by FavoriteMenu.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FavoriteMenuGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FavoriteMenuGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FavoriteMenuGroupByArgs['orderBy'] }
      : { orderBy?: FavoriteMenuGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FavoriteMenuGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFavoriteMenuGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FavoriteMenu model
 */
readonly fields: FavoriteMenuFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FavoriteMenu.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FavoriteMenuClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  pembeli<T extends Prisma.PembeliDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PembeliDefaultArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  menu<T extends Prisma.MenuDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MenuDefaultArgs<ExtArgs>>): Prisma.Prisma__MenuClient<runtime.Types.Result.GetResult<Prisma.$MenuPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FavoriteMenu model
 */
export interface FavoriteMenuFieldRefs {
  readonly id: Prisma.FieldRef<"FavoriteMenu", 'String'>
  readonly pembeliId: Prisma.FieldRef<"FavoriteMenu", 'String'>
  readonly menuId: Prisma.FieldRef<"FavoriteMenu", 'String'>
  readonly createdAt: Prisma.FieldRef<"FavoriteMenu", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FavoriteMenu findUnique
 */
export type FavoriteMenuFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteMenu to fetch.
   */
  where: Prisma.FavoriteMenuWhereUniqueInput
}

/**
 * FavoriteMenu findUniqueOrThrow
 */
export type FavoriteMenuFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteMenu to fetch.
   */
  where: Prisma.FavoriteMenuWhereUniqueInput
}

/**
 * FavoriteMenu findFirst
 */
export type FavoriteMenuFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteMenu to fetch.
   */
  where?: Prisma.FavoriteMenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteMenus to fetch.
   */
  orderBy?: Prisma.FavoriteMenuOrderByWithRelationInput | Prisma.FavoriteMenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FavoriteMenus.
   */
  cursor?: Prisma.FavoriteMenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteMenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteMenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteMenus.
   */
  distinct?: Prisma.FavoriteMenuScalarFieldEnum | Prisma.FavoriteMenuScalarFieldEnum[]
}

/**
 * FavoriteMenu findFirstOrThrow
 */
export type FavoriteMenuFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteMenu to fetch.
   */
  where?: Prisma.FavoriteMenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteMenus to fetch.
   */
  orderBy?: Prisma.FavoriteMenuOrderByWithRelationInput | Prisma.FavoriteMenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FavoriteMenus.
   */
  cursor?: Prisma.FavoriteMenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteMenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteMenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteMenus.
   */
  distinct?: Prisma.FavoriteMenuScalarFieldEnum | Prisma.FavoriteMenuScalarFieldEnum[]
}

/**
 * FavoriteMenu findMany
 */
export type FavoriteMenuFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * Filter, which FavoriteMenus to fetch.
   */
  where?: Prisma.FavoriteMenuWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FavoriteMenus to fetch.
   */
  orderBy?: Prisma.FavoriteMenuOrderByWithRelationInput | Prisma.FavoriteMenuOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FavoriteMenus.
   */
  cursor?: Prisma.FavoriteMenuWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FavoriteMenus from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FavoriteMenus.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FavoriteMenus.
   */
  distinct?: Prisma.FavoriteMenuScalarFieldEnum | Prisma.FavoriteMenuScalarFieldEnum[]
}

/**
 * FavoriteMenu create
 */
export type FavoriteMenuCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * The data needed to create a FavoriteMenu.
   */
  data: Prisma.XOR<Prisma.FavoriteMenuCreateInput, Prisma.FavoriteMenuUncheckedCreateInput>
}

/**
 * FavoriteMenu createMany
 */
export type FavoriteMenuCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FavoriteMenus.
   */
  data: Prisma.FavoriteMenuCreateManyInput | Prisma.FavoriteMenuCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FavoriteMenu update
 */
export type FavoriteMenuUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * The data needed to update a FavoriteMenu.
   */
  data: Prisma.XOR<Prisma.FavoriteMenuUpdateInput, Prisma.FavoriteMenuUncheckedUpdateInput>
  /**
   * Choose, which FavoriteMenu to update.
   */
  where: Prisma.FavoriteMenuWhereUniqueInput
}

/**
 * FavoriteMenu updateMany
 */
export type FavoriteMenuUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FavoriteMenus.
   */
  data: Prisma.XOR<Prisma.FavoriteMenuUpdateManyMutationInput, Prisma.FavoriteMenuUncheckedUpdateManyInput>
  /**
   * Filter which FavoriteMenus to update
   */
  where?: Prisma.FavoriteMenuWhereInput
  /**
   * Limit how many FavoriteMenus to update.
   */
  limit?: number
}

/**
 * FavoriteMenu upsert
 */
export type FavoriteMenuUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * The filter to search for the FavoriteMenu to update in case it exists.
   */
  where: Prisma.FavoriteMenuWhereUniqueInput
  /**
   * In case the FavoriteMenu found by the `where` argument doesn't exist, create a new FavoriteMenu with this data.
   */
  create: Prisma.XOR<Prisma.FavoriteMenuCreateInput, Prisma.FavoriteMenuUncheckedCreateInput>
  /**
   * In case the FavoriteMenu was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FavoriteMenuUpdateInput, Prisma.FavoriteMenuUncheckedUpdateInput>
}

/**
 * FavoriteMenu delete
 */
export type FavoriteMenuDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  /**
   * Filter which FavoriteMenu to delete.
   */
  where: Prisma.FavoriteMenuWhereUniqueInput
}

/**
 * FavoriteMenu deleteMany
 */
export type FavoriteMenuDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FavoriteMenus to delete
   */
  where?: Prisma.FavoriteMenuWhereInput
  /**
   * Limit how many FavoriteMenus to delete.
   */
  limit?: number
}

/**
 * FavoriteMenu without action
 */
export type FavoriteMenuDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
}
