
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Pembeli` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Pembeli
 * 
 */
export type PembeliModel = runtime.Types.Result.DefaultSelection<Prisma.$PembeliPayload>

export type AggregatePembeli = {
  _count: PembeliCountAggregateOutputType | null
  _avg: PembeliAvgAggregateOutputType | null
  _sum: PembeliSumAggregateOutputType | null
  _min: PembeliMinAggregateOutputType | null
  _max: PembeliMaxAggregateOutputType | null
}

export type PembeliAvgAggregateOutputType = {
  totalSpent: number | null
  totalOrders: number | null
  averageRating: number | null
}

export type PembeliSumAggregateOutputType = {
  totalSpent: number | null
  totalOrders: number | null
  averageRating: number | null
}

export type PembeliMinAggregateOutputType = {
  id: string | null
  userId: string | null
  fullName: string | null
  phone: string | null
  address: string | null
  city: string | null
  photoUrl: string | null
  totalSpent: number | null
  totalOrders: number | null
  averageRating: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PembeliMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  fullName: string | null
  phone: string | null
  address: string | null
  city: string | null
  photoUrl: string | null
  totalSpent: number | null
  totalOrders: number | null
  averageRating: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PembeliCountAggregateOutputType = {
  id: number
  userId: number
  fullName: number
  phone: number
  address: number
  city: number
  photoUrl: number
  totalSpent: number
  totalOrders: number
  averageRating: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PembeliAvgAggregateInputType = {
  totalSpent?: true
  totalOrders?: true
  averageRating?: true
}

export type PembeliSumAggregateInputType = {
  totalSpent?: true
  totalOrders?: true
  averageRating?: true
}

export type PembeliMinAggregateInputType = {
  id?: true
  userId?: true
  fullName?: true
  phone?: true
  address?: true
  city?: true
  photoUrl?: true
  totalSpent?: true
  totalOrders?: true
  averageRating?: true
  createdAt?: true
  updatedAt?: true
}

export type PembeliMaxAggregateInputType = {
  id?: true
  userId?: true
  fullName?: true
  phone?: true
  address?: true
  city?: true
  photoUrl?: true
  totalSpent?: true
  totalOrders?: true
  averageRating?: true
  createdAt?: true
  updatedAt?: true
}

export type PembeliCountAggregateInputType = {
  id?: true
  userId?: true
  fullName?: true
  phone?: true
  address?: true
  city?: true
  photoUrl?: true
  totalSpent?: true
  totalOrders?: true
  averageRating?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PembeliAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pembeli to aggregate.
   */
  where?: Prisma.PembeliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pembelis to fetch.
   */
  orderBy?: Prisma.PembeliOrderByWithRelationInput | Prisma.PembeliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PembeliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pembelis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pembelis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Pembelis
  **/
  _count?: true | PembeliCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PembeliAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PembeliSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PembeliMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PembeliMaxAggregateInputType
}

export type GetPembeliAggregateType<T extends PembeliAggregateArgs> = {
      [P in keyof T & keyof AggregatePembeli]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePembeli[P]>
    : Prisma.GetScalarType<T[P], AggregatePembeli[P]>
}




export type PembeliGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PembeliWhereInput
  orderBy?: Prisma.PembeliOrderByWithAggregationInput | Prisma.PembeliOrderByWithAggregationInput[]
  by: Prisma.PembeliScalarFieldEnum[] | Prisma.PembeliScalarFieldEnum
  having?: Prisma.PembeliScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PembeliCountAggregateInputType | true
  _avg?: PembeliAvgAggregateInputType
  _sum?: PembeliSumAggregateInputType
  _min?: PembeliMinAggregateInputType
  _max?: PembeliMaxAggregateInputType
}

export type PembeliGroupByOutputType = {
  id: string
  userId: string
  fullName: string
  phone: string
  address: string | null
  city: string | null
  photoUrl: string | null
  totalSpent: number
  totalOrders: number
  averageRating: number
  createdAt: Date
  updatedAt: Date
  _count: PembeliCountAggregateOutputType | null
  _avg: PembeliAvgAggregateOutputType | null
  _sum: PembeliSumAggregateOutputType | null
  _min: PembeliMinAggregateOutputType | null
  _max: PembeliMaxAggregateOutputType | null
}

export type GetPembeliGroupByPayload<T extends PembeliGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PembeliGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PembeliGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PembeliGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PembeliGroupByOutputType[P]>
      }
    >
  >



export type PembeliWhereInput = {
  AND?: Prisma.PembeliWhereInput | Prisma.PembeliWhereInput[]
  OR?: Prisma.PembeliWhereInput[]
  NOT?: Prisma.PembeliWhereInput | Prisma.PembeliWhereInput[]
  id?: Prisma.StringFilter<"Pembeli"> | string
  userId?: Prisma.StringFilter<"Pembeli"> | string
  fullName?: Prisma.StringFilter<"Pembeli"> | string
  phone?: Prisma.StringFilter<"Pembeli"> | string
  address?: Prisma.StringNullableFilter<"Pembeli"> | string | null
  city?: Prisma.StringNullableFilter<"Pembeli"> | string | null
  photoUrl?: Prisma.StringNullableFilter<"Pembeli"> | string | null
  totalSpent?: Prisma.FloatFilter<"Pembeli"> | number
  totalOrders?: Prisma.IntFilter<"Pembeli"> | number
  averageRating?: Prisma.FloatFilter<"Pembeli"> | number
  createdAt?: Prisma.DateTimeFilter<"Pembeli"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pembeli"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  carts?: Prisma.CartItemListRelationFilter
  orders?: Prisma.OrderListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
  favoriteMenus?: Prisma.FavoriteMenuListRelationFilter
  address_?: Prisma.AddressListRelationFilter
}

export type PembeliOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  photoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  carts?: Prisma.CartItemOrderByRelationAggregateInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
  reviews?: Prisma.ReviewOrderByRelationAggregateInput
  favoriteMenus?: Prisma.FavoriteMenuOrderByRelationAggregateInput
  address_?: Prisma.AddressOrderByRelationAggregateInput
  _relevance?: Prisma.PembeliOrderByRelevanceInput
}

export type PembeliWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  phone?: string
  AND?: Prisma.PembeliWhereInput | Prisma.PembeliWhereInput[]
  OR?: Prisma.PembeliWhereInput[]
  NOT?: Prisma.PembeliWhereInput | Prisma.PembeliWhereInput[]
  fullName?: Prisma.StringFilter<"Pembeli"> | string
  address?: Prisma.StringNullableFilter<"Pembeli"> | string | null
  city?: Prisma.StringNullableFilter<"Pembeli"> | string | null
  photoUrl?: Prisma.StringNullableFilter<"Pembeli"> | string | null
  totalSpent?: Prisma.FloatFilter<"Pembeli"> | number
  totalOrders?: Prisma.IntFilter<"Pembeli"> | number
  averageRating?: Prisma.FloatFilter<"Pembeli"> | number
  createdAt?: Prisma.DateTimeFilter<"Pembeli"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Pembeli"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  carts?: Prisma.CartItemListRelationFilter
  orders?: Prisma.OrderListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
  favoriteMenus?: Prisma.FavoriteMenuListRelationFilter
  address_?: Prisma.AddressListRelationFilter
}, "id" | "userId" | "phone">

export type PembeliOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrderInput | Prisma.SortOrder
  photoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PembeliCountOrderByAggregateInput
  _avg?: Prisma.PembeliAvgOrderByAggregateInput
  _max?: Prisma.PembeliMaxOrderByAggregateInput
  _min?: Prisma.PembeliMinOrderByAggregateInput
  _sum?: Prisma.PembeliSumOrderByAggregateInput
}

export type PembeliScalarWhereWithAggregatesInput = {
  AND?: Prisma.PembeliScalarWhereWithAggregatesInput | Prisma.PembeliScalarWhereWithAggregatesInput[]
  OR?: Prisma.PembeliScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PembeliScalarWhereWithAggregatesInput | Prisma.PembeliScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Pembeli"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Pembeli"> | string
  fullName?: Prisma.StringWithAggregatesFilter<"Pembeli"> | string
  phone?: Prisma.StringWithAggregatesFilter<"Pembeli"> | string
  address?: Prisma.StringNullableWithAggregatesFilter<"Pembeli"> | string | null
  city?: Prisma.StringNullableWithAggregatesFilter<"Pembeli"> | string | null
  photoUrl?: Prisma.StringNullableWithAggregatesFilter<"Pembeli"> | string | null
  totalSpent?: Prisma.FloatWithAggregatesFilter<"Pembeli"> | number
  totalOrders?: Prisma.IntWithAggregatesFilter<"Pembeli"> | number
  averageRating?: Prisma.FloatWithAggregatesFilter<"Pembeli"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Pembeli"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Pembeli"> | Date | string
}

export type PembeliCreateInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPembeliInput
  carts?: Prisma.CartItemCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateInput = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemUncheckedCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPembeliNestedInput
  carts?: Prisma.CartItemUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUncheckedUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUncheckedUpdateManyWithoutPembeliNestedInput
}

export type PembeliCreateManyInput = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PembeliUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PembeliUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PembeliNullableScalarRelationFilter = {
  is?: Prisma.PembeliWhereInput | null
  isNot?: Prisma.PembeliWhereInput | null
}

export type PembeliOrderByRelevanceInput = {
  fields: Prisma.PembeliOrderByRelevanceFieldEnum | Prisma.PembeliOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PembeliCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PembeliAvgOrderByAggregateInput = {
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
}

export type PembeliMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PembeliMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PembeliSumOrderByAggregateInput = {
  totalSpent?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
}

export type PembeliScalarRelationFilter = {
  is?: Prisma.PembeliWhereInput
  isNot?: Prisma.PembeliWhereInput
}

export type PembeliCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutUserInput, Prisma.PembeliUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutUserInput
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutUserInput, Prisma.PembeliUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutUserInput
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutUserInput, Prisma.PembeliUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutUserInput
  upsert?: Prisma.PembeliUpsertWithoutUserInput
  disconnect?: Prisma.PembeliWhereInput | boolean
  delete?: Prisma.PembeliWhereInput | boolean
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutUserInput, Prisma.PembeliUpdateWithoutUserInput>, Prisma.PembeliUncheckedUpdateWithoutUserInput>
}

export type PembeliUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutUserInput, Prisma.PembeliUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutUserInput
  upsert?: Prisma.PembeliUpsertWithoutUserInput
  disconnect?: Prisma.PembeliWhereInput | boolean
  delete?: Prisma.PembeliWhereInput | boolean
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutUserInput, Prisma.PembeliUpdateWithoutUserInput>, Prisma.PembeliUncheckedUpdateWithoutUserInput>
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PembeliCreateNestedOneWithoutCartsInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutCartsInput, Prisma.PembeliUncheckedCreateWithoutCartsInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutCartsInput
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUpdateOneRequiredWithoutCartsNestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutCartsInput, Prisma.PembeliUncheckedCreateWithoutCartsInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutCartsInput
  upsert?: Prisma.PembeliUpsertWithoutCartsInput
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutCartsInput, Prisma.PembeliUpdateWithoutCartsInput>, Prisma.PembeliUncheckedUpdateWithoutCartsInput>
}

export type PembeliCreateNestedOneWithoutFavoriteMenusInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutFavoriteMenusInput, Prisma.PembeliUncheckedCreateWithoutFavoriteMenusInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutFavoriteMenusInput
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUpdateOneRequiredWithoutFavoriteMenusNestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutFavoriteMenusInput, Prisma.PembeliUncheckedCreateWithoutFavoriteMenusInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutFavoriteMenusInput
  upsert?: Prisma.PembeliUpsertWithoutFavoriteMenusInput
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutFavoriteMenusInput, Prisma.PembeliUpdateWithoutFavoriteMenusInput>, Prisma.PembeliUncheckedUpdateWithoutFavoriteMenusInput>
}

export type PembeliCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutOrdersInput, Prisma.PembeliUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutOrdersInput
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUpdateOneRequiredWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutOrdersInput, Prisma.PembeliUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.PembeliUpsertWithoutOrdersInput
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutOrdersInput, Prisma.PembeliUpdateWithoutOrdersInput>, Prisma.PembeliUncheckedUpdateWithoutOrdersInput>
}

export type PembeliCreateNestedOneWithoutReviewsInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutReviewsInput, Prisma.PembeliUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutReviewsInput
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUpdateOneRequiredWithoutReviewsNestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutReviewsInput, Prisma.PembeliUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutReviewsInput
  upsert?: Prisma.PembeliUpsertWithoutReviewsInput
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutReviewsInput, Prisma.PembeliUpdateWithoutReviewsInput>, Prisma.PembeliUncheckedUpdateWithoutReviewsInput>
}

export type PembeliCreateNestedOneWithoutAddress_Input = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutAddress_Input, Prisma.PembeliUncheckedCreateWithoutAddress_Input>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutAddress_Input
  connect?: Prisma.PembeliWhereUniqueInput
}

export type PembeliUpdateOneRequiredWithoutAddress_NestedInput = {
  create?: Prisma.XOR<Prisma.PembeliCreateWithoutAddress_Input, Prisma.PembeliUncheckedCreateWithoutAddress_Input>
  connectOrCreate?: Prisma.PembeliCreateOrConnectWithoutAddress_Input
  upsert?: Prisma.PembeliUpsertWithoutAddress_Input
  connect?: Prisma.PembeliWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PembeliUpdateToOneWithWhereWithoutAddress_Input, Prisma.PembeliUpdateWithoutAddress_Input>, Prisma.PembeliUncheckedUpdateWithoutAddress_Input>
}

export type PembeliCreateWithoutUserInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateWithoutUserInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemUncheckedCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliCreateOrConnectWithoutUserInput = {
  where: Prisma.PembeliWhereUniqueInput
  create: Prisma.XOR<Prisma.PembeliCreateWithoutUserInput, Prisma.PembeliUncheckedCreateWithoutUserInput>
}

export type PembeliUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.PembeliUpdateWithoutUserInput, Prisma.PembeliUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PembeliCreateWithoutUserInput, Prisma.PembeliUncheckedCreateWithoutUserInput>
  where?: Prisma.PembeliWhereInput
}

export type PembeliUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.PembeliWhereInput
  data: Prisma.XOR<Prisma.PembeliUpdateWithoutUserInput, Prisma.PembeliUncheckedUpdateWithoutUserInput>
}

export type PembeliUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUncheckedUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUncheckedUpdateManyWithoutPembeliNestedInput
}

export type PembeliCreateWithoutCartsInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPembeliInput
  orders?: Prisma.OrderCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateWithoutCartsInput = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliCreateOrConnectWithoutCartsInput = {
  where: Prisma.PembeliWhereUniqueInput
  create: Prisma.XOR<Prisma.PembeliCreateWithoutCartsInput, Prisma.PembeliUncheckedCreateWithoutCartsInput>
}

export type PembeliUpsertWithoutCartsInput = {
  update: Prisma.XOR<Prisma.PembeliUpdateWithoutCartsInput, Prisma.PembeliUncheckedUpdateWithoutCartsInput>
  create: Prisma.XOR<Prisma.PembeliCreateWithoutCartsInput, Prisma.PembeliUncheckedCreateWithoutCartsInput>
  where?: Prisma.PembeliWhereInput
}

export type PembeliUpdateToOneWithWhereWithoutCartsInput = {
  where?: Prisma.PembeliWhereInput
  data: Prisma.XOR<Prisma.PembeliUpdateWithoutCartsInput, Prisma.PembeliUncheckedUpdateWithoutCartsInput>
}

export type PembeliUpdateWithoutCartsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPembeliNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateWithoutCartsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUncheckedUpdateManyWithoutPembeliNestedInput
}

export type PembeliCreateWithoutFavoriteMenusInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPembeliInput
  carts?: Prisma.CartItemCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateWithoutFavoriteMenusInput = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemUncheckedCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliCreateOrConnectWithoutFavoriteMenusInput = {
  where: Prisma.PembeliWhereUniqueInput
  create: Prisma.XOR<Prisma.PembeliCreateWithoutFavoriteMenusInput, Prisma.PembeliUncheckedCreateWithoutFavoriteMenusInput>
}

export type PembeliUpsertWithoutFavoriteMenusInput = {
  update: Prisma.XOR<Prisma.PembeliUpdateWithoutFavoriteMenusInput, Prisma.PembeliUncheckedUpdateWithoutFavoriteMenusInput>
  create: Prisma.XOR<Prisma.PembeliCreateWithoutFavoriteMenusInput, Prisma.PembeliUncheckedCreateWithoutFavoriteMenusInput>
  where?: Prisma.PembeliWhereInput
}

export type PembeliUpdateToOneWithWhereWithoutFavoriteMenusInput = {
  where?: Prisma.PembeliWhereInput
  data: Prisma.XOR<Prisma.PembeliUpdateWithoutFavoriteMenusInput, Prisma.PembeliUncheckedUpdateWithoutFavoriteMenusInput>
}

export type PembeliUpdateWithoutFavoriteMenusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPembeliNestedInput
  carts?: Prisma.CartItemUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateWithoutFavoriteMenusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUncheckedUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUncheckedUpdateManyWithoutPembeliNestedInput
}

export type PembeliCreateWithoutOrdersInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPembeliInput
  carts?: Prisma.CartItemCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateWithoutOrdersInput = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemUncheckedCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliCreateOrConnectWithoutOrdersInput = {
  where: Prisma.PembeliWhereUniqueInput
  create: Prisma.XOR<Prisma.PembeliCreateWithoutOrdersInput, Prisma.PembeliUncheckedCreateWithoutOrdersInput>
}

export type PembeliUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.PembeliUpdateWithoutOrdersInput, Prisma.PembeliUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.PembeliCreateWithoutOrdersInput, Prisma.PembeliUncheckedCreateWithoutOrdersInput>
  where?: Prisma.PembeliWhereInput
}

export type PembeliUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.PembeliWhereInput
  data: Prisma.XOR<Prisma.PembeliUpdateWithoutOrdersInput, Prisma.PembeliUncheckedUpdateWithoutOrdersInput>
}

export type PembeliUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPembeliNestedInput
  carts?: Prisma.CartItemUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUncheckedUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUncheckedUpdateManyWithoutPembeliNestedInput
}

export type PembeliCreateWithoutReviewsInput = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPembeliInput
  carts?: Prisma.CartItemCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateWithoutReviewsInput = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemUncheckedCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput
  address_?: Prisma.AddressUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliCreateOrConnectWithoutReviewsInput = {
  where: Prisma.PembeliWhereUniqueInput
  create: Prisma.XOR<Prisma.PembeliCreateWithoutReviewsInput, Prisma.PembeliUncheckedCreateWithoutReviewsInput>
}

export type PembeliUpsertWithoutReviewsInput = {
  update: Prisma.XOR<Prisma.PembeliUpdateWithoutReviewsInput, Prisma.PembeliUncheckedUpdateWithoutReviewsInput>
  create: Prisma.XOR<Prisma.PembeliCreateWithoutReviewsInput, Prisma.PembeliUncheckedCreateWithoutReviewsInput>
  where?: Prisma.PembeliWhereInput
}

export type PembeliUpdateToOneWithWhereWithoutReviewsInput = {
  where?: Prisma.PembeliWhereInput
  data: Prisma.XOR<Prisma.PembeliUpdateWithoutReviewsInput, Prisma.PembeliUncheckedUpdateWithoutReviewsInput>
}

export type PembeliUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPembeliNestedInput
  carts?: Prisma.CartItemUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUncheckedUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput
  address_?: Prisma.AddressUncheckedUpdateManyWithoutPembeliNestedInput
}

export type PembeliCreateWithoutAddress_Input = {
  id?: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPembeliInput
  carts?: Prisma.CartItemCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuCreateNestedManyWithoutPembeliInput
}

export type PembeliUncheckedCreateWithoutAddress_Input = {
  id?: string
  userId: string
  fullName: string
  phone: string
  address?: string | null
  city?: string | null
  photoUrl?: string | null
  totalSpent?: number
  totalOrders?: number
  averageRating?: number
  createdAt?: Date | string
  updatedAt?: Date | string
  carts?: Prisma.CartItemUncheckedCreateNestedManyWithoutPembeliInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPembeliInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPembeliInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedCreateNestedManyWithoutPembeliInput
}

export type PembeliCreateOrConnectWithoutAddress_Input = {
  where: Prisma.PembeliWhereUniqueInput
  create: Prisma.XOR<Prisma.PembeliCreateWithoutAddress_Input, Prisma.PembeliUncheckedCreateWithoutAddress_Input>
}

export type PembeliUpsertWithoutAddress_Input = {
  update: Prisma.XOR<Prisma.PembeliUpdateWithoutAddress_Input, Prisma.PembeliUncheckedUpdateWithoutAddress_Input>
  create: Prisma.XOR<Prisma.PembeliCreateWithoutAddress_Input, Prisma.PembeliUncheckedCreateWithoutAddress_Input>
  where?: Prisma.PembeliWhereInput
}

export type PembeliUpdateToOneWithWhereWithoutAddress_Input = {
  where?: Prisma.PembeliWhereInput
  data: Prisma.XOR<Prisma.PembeliUpdateWithoutAddress_Input, Prisma.PembeliUncheckedUpdateWithoutAddress_Input>
}

export type PembeliUpdateWithoutAddress_Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPembeliNestedInput
  carts?: Prisma.CartItemUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUpdateManyWithoutPembeliNestedInput
}

export type PembeliUncheckedUpdateWithoutAddress_Input = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  fullName?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalSpent?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  carts?: Prisma.CartItemUncheckedUpdateManyWithoutPembeliNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPembeliNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPembeliNestedInput
  favoriteMenus?: Prisma.FavoriteMenuUncheckedUpdateManyWithoutPembeliNestedInput
}


/**
 * Count Type PembeliCountOutputType
 */

export type PembeliCountOutputType = {
  carts: number
  orders: number
  reviews: number
  favoriteMenus: number
  address_: number
}

export type PembeliCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  carts?: boolean | PembeliCountOutputTypeCountCartsArgs
  orders?: boolean | PembeliCountOutputTypeCountOrdersArgs
  reviews?: boolean | PembeliCountOutputTypeCountReviewsArgs
  favoriteMenus?: boolean | PembeliCountOutputTypeCountFavoriteMenusArgs
  address_?: boolean | PembeliCountOutputTypeCountAddress_Args
}

/**
 * PembeliCountOutputType without action
 */
export type PembeliCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PembeliCountOutputType
   */
  select?: Prisma.PembeliCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PembeliCountOutputType without action
 */
export type PembeliCountOutputTypeCountCartsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CartItemWhereInput
}

/**
 * PembeliCountOutputType without action
 */
export type PembeliCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * PembeliCountOutputType without action
 */
export type PembeliCountOutputTypeCountReviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewWhereInput
}

/**
 * PembeliCountOutputType without action
 */
export type PembeliCountOutputTypeCountFavoriteMenusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteMenuWhereInput
}

/**
 * PembeliCountOutputType without action
 */
export type PembeliCountOutputTypeCountAddress_Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AddressWhereInput
}


export type PembeliSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  fullName?: boolean
  phone?: boolean
  address?: boolean
  city?: boolean
  photoUrl?: boolean
  totalSpent?: boolean
  totalOrders?: boolean
  averageRating?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  carts?: boolean | Prisma.Pembeli$cartsArgs<ExtArgs>
  orders?: boolean | Prisma.Pembeli$ordersArgs<ExtArgs>
  reviews?: boolean | Prisma.Pembeli$reviewsArgs<ExtArgs>
  favoriteMenus?: boolean | Prisma.Pembeli$favoriteMenusArgs<ExtArgs>
  address_?: boolean | Prisma.Pembeli$address_Args<ExtArgs>
  _count?: boolean | Prisma.PembeliCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pembeli"]>



export type PembeliSelectScalar = {
  id?: boolean
  userId?: boolean
  fullName?: boolean
  phone?: boolean
  address?: boolean
  city?: boolean
  photoUrl?: boolean
  totalSpent?: boolean
  totalOrders?: boolean
  averageRating?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PembeliOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "fullName" | "phone" | "address" | "city" | "photoUrl" | "totalSpent" | "totalOrders" | "averageRating" | "createdAt" | "updatedAt", ExtArgs["result"]["pembeli"]>
export type PembeliInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  carts?: boolean | Prisma.Pembeli$cartsArgs<ExtArgs>
  orders?: boolean | Prisma.Pembeli$ordersArgs<ExtArgs>
  reviews?: boolean | Prisma.Pembeli$reviewsArgs<ExtArgs>
  favoriteMenus?: boolean | Prisma.Pembeli$favoriteMenusArgs<ExtArgs>
  address_?: boolean | Prisma.Pembeli$address_Args<ExtArgs>
  _count?: boolean | Prisma.PembeliCountOutputTypeDefaultArgs<ExtArgs>
}

export type $PembeliPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Pembeli"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    carts: Prisma.$CartItemPayload<ExtArgs>[]
    orders: Prisma.$OrderPayload<ExtArgs>[]
    reviews: Prisma.$ReviewPayload<ExtArgs>[]
    favoriteMenus: Prisma.$FavoriteMenuPayload<ExtArgs>[]
    address_: Prisma.$AddressPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    fullName: string
    phone: string
    address: string | null
    city: string | null
    photoUrl: string | null
    totalSpent: number
    totalOrders: number
    averageRating: number
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["pembeli"]>
  composites: {}
}

export type PembeliGetPayload<S extends boolean | null | undefined | PembeliDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PembeliPayload, S>

export type PembeliCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PembeliFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PembeliCountAggregateInputType | true
  }

export interface PembeliDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Pembeli'], meta: { name: 'Pembeli' } }
  /**
   * Find zero or one Pembeli that matches the filter.
   * @param {PembeliFindUniqueArgs} args - Arguments to find a Pembeli
   * @example
   * // Get one Pembeli
   * const pembeli = await prisma.pembeli.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PembeliFindUniqueArgs>(args: Prisma.SelectSubset<T, PembeliFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Pembeli that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PembeliFindUniqueOrThrowArgs} args - Arguments to find a Pembeli
   * @example
   * // Get one Pembeli
   * const pembeli = await prisma.pembeli.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PembeliFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PembeliFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pembeli that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliFindFirstArgs} args - Arguments to find a Pembeli
   * @example
   * // Get one Pembeli
   * const pembeli = await prisma.pembeli.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PembeliFindFirstArgs>(args?: Prisma.SelectSubset<T, PembeliFindFirstArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Pembeli that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliFindFirstOrThrowArgs} args - Arguments to find a Pembeli
   * @example
   * // Get one Pembeli
   * const pembeli = await prisma.pembeli.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PembeliFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PembeliFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Pembelis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Pembelis
   * const pembelis = await prisma.pembeli.findMany()
   * 
   * // Get first 10 Pembelis
   * const pembelis = await prisma.pembeli.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pembeliWithIdOnly = await prisma.pembeli.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PembeliFindManyArgs>(args?: Prisma.SelectSubset<T, PembeliFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Pembeli.
   * @param {PembeliCreateArgs} args - Arguments to create a Pembeli.
   * @example
   * // Create one Pembeli
   * const Pembeli = await prisma.pembeli.create({
   *   data: {
   *     // ... data to create a Pembeli
   *   }
   * })
   * 
   */
  create<T extends PembeliCreateArgs>(args: Prisma.SelectSubset<T, PembeliCreateArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Pembelis.
   * @param {PembeliCreateManyArgs} args - Arguments to create many Pembelis.
   * @example
   * // Create many Pembelis
   * const pembeli = await prisma.pembeli.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PembeliCreateManyArgs>(args?: Prisma.SelectSubset<T, PembeliCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Pembeli.
   * @param {PembeliDeleteArgs} args - Arguments to delete one Pembeli.
   * @example
   * // Delete one Pembeli
   * const Pembeli = await prisma.pembeli.delete({
   *   where: {
   *     // ... filter to delete one Pembeli
   *   }
   * })
   * 
   */
  delete<T extends PembeliDeleteArgs>(args: Prisma.SelectSubset<T, PembeliDeleteArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Pembeli.
   * @param {PembeliUpdateArgs} args - Arguments to update one Pembeli.
   * @example
   * // Update one Pembeli
   * const pembeli = await prisma.pembeli.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PembeliUpdateArgs>(args: Prisma.SelectSubset<T, PembeliUpdateArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Pembelis.
   * @param {PembeliDeleteManyArgs} args - Arguments to filter Pembelis to delete.
   * @example
   * // Delete a few Pembelis
   * const { count } = await prisma.pembeli.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PembeliDeleteManyArgs>(args?: Prisma.SelectSubset<T, PembeliDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Pembelis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Pembelis
   * const pembeli = await prisma.pembeli.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PembeliUpdateManyArgs>(args: Prisma.SelectSubset<T, PembeliUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Pembeli.
   * @param {PembeliUpsertArgs} args - Arguments to update or create a Pembeli.
   * @example
   * // Update or create a Pembeli
   * const pembeli = await prisma.pembeli.upsert({
   *   create: {
   *     // ... data to create a Pembeli
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Pembeli we want to update
   *   }
   * })
   */
  upsert<T extends PembeliUpsertArgs>(args: Prisma.SelectSubset<T, PembeliUpsertArgs<ExtArgs>>): Prisma.Prisma__PembeliClient<runtime.Types.Result.GetResult<Prisma.$PembeliPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Pembelis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliCountArgs} args - Arguments to filter Pembelis to count.
   * @example
   * // Count the number of Pembelis
   * const count = await prisma.pembeli.count({
   *   where: {
   *     // ... the filter for the Pembelis we want to count
   *   }
   * })
  **/
  count<T extends PembeliCountArgs>(
    args?: Prisma.Subset<T, PembeliCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PembeliCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Pembeli.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PembeliAggregateArgs>(args: Prisma.Subset<T, PembeliAggregateArgs>): Prisma.PrismaPromise<GetPembeliAggregateType<T>>

  /**
   * Group by Pembeli.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PembeliGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PembeliGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PembeliGroupByArgs['orderBy'] }
      : { orderBy?: PembeliGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PembeliGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPembeliGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Pembeli model
 */
readonly fields: PembeliFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Pembeli.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PembeliClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  carts<T extends Prisma.Pembeli$cartsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pembeli$cartsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CartItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.Pembeli$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pembeli$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reviews<T extends Prisma.Pembeli$reviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pembeli$reviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  favoriteMenus<T extends Prisma.Pembeli$favoriteMenusArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pembeli$favoriteMenusArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoriteMenuPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  address_<T extends Prisma.Pembeli$address_Args<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Pembeli$address_Args<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AddressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Pembeli model
 */
export interface PembeliFieldRefs {
  readonly id: Prisma.FieldRef<"Pembeli", 'String'>
  readonly userId: Prisma.FieldRef<"Pembeli", 'String'>
  readonly fullName: Prisma.FieldRef<"Pembeli", 'String'>
  readonly phone: Prisma.FieldRef<"Pembeli", 'String'>
  readonly address: Prisma.FieldRef<"Pembeli", 'String'>
  readonly city: Prisma.FieldRef<"Pembeli", 'String'>
  readonly photoUrl: Prisma.FieldRef<"Pembeli", 'String'>
  readonly totalSpent: Prisma.FieldRef<"Pembeli", 'Float'>
  readonly totalOrders: Prisma.FieldRef<"Pembeli", 'Int'>
  readonly averageRating: Prisma.FieldRef<"Pembeli", 'Float'>
  readonly createdAt: Prisma.FieldRef<"Pembeli", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Pembeli", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Pembeli findUnique
 */
export type PembeliFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * Filter, which Pembeli to fetch.
   */
  where: Prisma.PembeliWhereUniqueInput
}

/**
 * Pembeli findUniqueOrThrow
 */
export type PembeliFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * Filter, which Pembeli to fetch.
   */
  where: Prisma.PembeliWhereUniqueInput
}

/**
 * Pembeli findFirst
 */
export type PembeliFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * Filter, which Pembeli to fetch.
   */
  where?: Prisma.PembeliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pembelis to fetch.
   */
  orderBy?: Prisma.PembeliOrderByWithRelationInput | Prisma.PembeliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pembelis.
   */
  cursor?: Prisma.PembeliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pembelis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pembelis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pembelis.
   */
  distinct?: Prisma.PembeliScalarFieldEnum | Prisma.PembeliScalarFieldEnum[]
}

/**
 * Pembeli findFirstOrThrow
 */
export type PembeliFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * Filter, which Pembeli to fetch.
   */
  where?: Prisma.PembeliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pembelis to fetch.
   */
  orderBy?: Prisma.PembeliOrderByWithRelationInput | Prisma.PembeliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Pembelis.
   */
  cursor?: Prisma.PembeliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pembelis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pembelis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pembelis.
   */
  distinct?: Prisma.PembeliScalarFieldEnum | Prisma.PembeliScalarFieldEnum[]
}

/**
 * Pembeli findMany
 */
export type PembeliFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * Filter, which Pembelis to fetch.
   */
  where?: Prisma.PembeliWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Pembelis to fetch.
   */
  orderBy?: Prisma.PembeliOrderByWithRelationInput | Prisma.PembeliOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Pembelis.
   */
  cursor?: Prisma.PembeliWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Pembelis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Pembelis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Pembelis.
   */
  distinct?: Prisma.PembeliScalarFieldEnum | Prisma.PembeliScalarFieldEnum[]
}

/**
 * Pembeli create
 */
export type PembeliCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * The data needed to create a Pembeli.
   */
  data: Prisma.XOR<Prisma.PembeliCreateInput, Prisma.PembeliUncheckedCreateInput>
}

/**
 * Pembeli createMany
 */
export type PembeliCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Pembelis.
   */
  data: Prisma.PembeliCreateManyInput | Prisma.PembeliCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Pembeli update
 */
export type PembeliUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * The data needed to update a Pembeli.
   */
  data: Prisma.XOR<Prisma.PembeliUpdateInput, Prisma.PembeliUncheckedUpdateInput>
  /**
   * Choose, which Pembeli to update.
   */
  where: Prisma.PembeliWhereUniqueInput
}

/**
 * Pembeli updateMany
 */
export type PembeliUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Pembelis.
   */
  data: Prisma.XOR<Prisma.PembeliUpdateManyMutationInput, Prisma.PembeliUncheckedUpdateManyInput>
  /**
   * Filter which Pembelis to update
   */
  where?: Prisma.PembeliWhereInput
  /**
   * Limit how many Pembelis to update.
   */
  limit?: number
}

/**
 * Pembeli upsert
 */
export type PembeliUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * The filter to search for the Pembeli to update in case it exists.
   */
  where: Prisma.PembeliWhereUniqueInput
  /**
   * In case the Pembeli found by the `where` argument doesn't exist, create a new Pembeli with this data.
   */
  create: Prisma.XOR<Prisma.PembeliCreateInput, Prisma.PembeliUncheckedCreateInput>
  /**
   * In case the Pembeli was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PembeliUpdateInput, Prisma.PembeliUncheckedUpdateInput>
}

/**
 * Pembeli delete
 */
export type PembeliDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
  /**
   * Filter which Pembeli to delete.
   */
  where: Prisma.PembeliWhereUniqueInput
}

/**
 * Pembeli deleteMany
 */
export type PembeliDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Pembelis to delete
   */
  where?: Prisma.PembeliWhereInput
  /**
   * Limit how many Pembelis to delete.
   */
  limit?: number
}

/**
 * Pembeli.carts
 */
export type Pembeli$cartsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CartItem
   */
  select?: Prisma.CartItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CartItem
   */
  omit?: Prisma.CartItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CartItemInclude<ExtArgs> | null
  where?: Prisma.CartItemWhereInput
  orderBy?: Prisma.CartItemOrderByWithRelationInput | Prisma.CartItemOrderByWithRelationInput[]
  cursor?: Prisma.CartItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CartItemScalarFieldEnum | Prisma.CartItemScalarFieldEnum[]
}

/**
 * Pembeli.orders
 */
export type Pembeli$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Pembeli.reviews
 */
export type Pembeli$reviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Review
   */
  select?: Prisma.ReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Review
   */
  omit?: Prisma.ReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewInclude<ExtArgs> | null
  where?: Prisma.ReviewWhereInput
  orderBy?: Prisma.ReviewOrderByWithRelationInput | Prisma.ReviewOrderByWithRelationInput[]
  cursor?: Prisma.ReviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * Pembeli.favoriteMenus
 */
export type Pembeli$favoriteMenusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FavoriteMenu
   */
  select?: Prisma.FavoriteMenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FavoriteMenu
   */
  omit?: Prisma.FavoriteMenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteMenuInclude<ExtArgs> | null
  where?: Prisma.FavoriteMenuWhereInput
  orderBy?: Prisma.FavoriteMenuOrderByWithRelationInput | Prisma.FavoriteMenuOrderByWithRelationInput[]
  cursor?: Prisma.FavoriteMenuWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FavoriteMenuScalarFieldEnum | Prisma.FavoriteMenuScalarFieldEnum[]
}

/**
 * Pembeli.address_
 */
export type Pembeli$address_Args<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Address
   */
  select?: Prisma.AddressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Address
   */
  omit?: Prisma.AddressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AddressInclude<ExtArgs> | null
  where?: Prisma.AddressWhereInput
  orderBy?: Prisma.AddressOrderByWithRelationInput | Prisma.AddressOrderByWithRelationInput[]
  cursor?: Prisma.AddressWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AddressScalarFieldEnum | Prisma.AddressScalarFieldEnum[]
}

/**
 * Pembeli without action
 */
export type PembeliDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Pembeli
   */
  select?: Prisma.PembeliSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Pembeli
   */
  omit?: Prisma.PembeliOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PembeliInclude<ExtArgs> | null
}
