
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Penjual` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Penjual
 * 
 */
export type PenjualModel = runtime.Types.Result.DefaultSelection<Prisma.$PenjualPayload>

export type AggregatePenjual = {
  _count: PenjualCountAggregateOutputType | null
  _avg: PenjualAvgAggregateOutputType | null
  _sum: PenjualSumAggregateOutputType | null
  _min: PenjualMinAggregateOutputType | null
  _max: PenjualMaxAggregateOutputType | null
}

export type PenjualAvgAggregateOutputType = {
  averageRating: number | null
  totalReviews: number | null
  totalSales: number | null
  totalOrders: number | null
}

export type PenjualSumAggregateOutputType = {
  averageRating: number | null
  totalReviews: number | null
  totalSales: number | null
  totalOrders: number | null
}

export type PenjualMinAggregateOutputType = {
  id: string | null
  userId: string | null
  businessName: string | null
  description: string | null
  phone: string | null
  address: string | null
  city: string | null
  photoUrl: string | null
  averageRating: number | null
  totalReviews: number | null
  totalSales: number | null
  totalOrders: number | null
  isVerified: boolean | null
  isOpen: boolean | null
  operatingHours: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PenjualMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  businessName: string | null
  description: string | null
  phone: string | null
  address: string | null
  city: string | null
  photoUrl: string | null
  averageRating: number | null
  totalReviews: number | null
  totalSales: number | null
  totalOrders: number | null
  isVerified: boolean | null
  isOpen: boolean | null
  operatingHours: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PenjualCountAggregateOutputType = {
  id: number
  userId: number
  businessName: number
  description: number
  phone: number
  address: number
  city: number
  photoUrl: number
  averageRating: number
  totalReviews: number
  totalSales: number
  totalOrders: number
  isVerified: number
  isOpen: number
  operatingHours: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PenjualAvgAggregateInputType = {
  averageRating?: true
  totalReviews?: true
  totalSales?: true
  totalOrders?: true
}

export type PenjualSumAggregateInputType = {
  averageRating?: true
  totalReviews?: true
  totalSales?: true
  totalOrders?: true
}

export type PenjualMinAggregateInputType = {
  id?: true
  userId?: true
  businessName?: true
  description?: true
  phone?: true
  address?: true
  city?: true
  photoUrl?: true
  averageRating?: true
  totalReviews?: true
  totalSales?: true
  totalOrders?: true
  isVerified?: true
  isOpen?: true
  operatingHours?: true
  createdAt?: true
  updatedAt?: true
}

export type PenjualMaxAggregateInputType = {
  id?: true
  userId?: true
  businessName?: true
  description?: true
  phone?: true
  address?: true
  city?: true
  photoUrl?: true
  averageRating?: true
  totalReviews?: true
  totalSales?: true
  totalOrders?: true
  isVerified?: true
  isOpen?: true
  operatingHours?: true
  createdAt?: true
  updatedAt?: true
}

export type PenjualCountAggregateInputType = {
  id?: true
  userId?: true
  businessName?: true
  description?: true
  phone?: true
  address?: true
  city?: true
  photoUrl?: true
  averageRating?: true
  totalReviews?: true
  totalSales?: true
  totalOrders?: true
  isVerified?: true
  isOpen?: true
  operatingHours?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PenjualAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Penjual to aggregate.
   */
  where?: Prisma.PenjualWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penjuals to fetch.
   */
  orderBy?: Prisma.PenjualOrderByWithRelationInput | Prisma.PenjualOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PenjualWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penjuals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penjuals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Penjuals
  **/
  _count?: true | PenjualCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PenjualAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PenjualSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PenjualMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PenjualMaxAggregateInputType
}

export type GetPenjualAggregateType<T extends PenjualAggregateArgs> = {
      [P in keyof T & keyof AggregatePenjual]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePenjual[P]>
    : Prisma.GetScalarType<T[P], AggregatePenjual[P]>
}




export type PenjualGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PenjualWhereInput
  orderBy?: Prisma.PenjualOrderByWithAggregationInput | Prisma.PenjualOrderByWithAggregationInput[]
  by: Prisma.PenjualScalarFieldEnum[] | Prisma.PenjualScalarFieldEnum
  having?: Prisma.PenjualScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PenjualCountAggregateInputType | true
  _avg?: PenjualAvgAggregateInputType
  _sum?: PenjualSumAggregateInputType
  _min?: PenjualMinAggregateInputType
  _max?: PenjualMaxAggregateInputType
}

export type PenjualGroupByOutputType = {
  id: string
  userId: string
  businessName: string
  description: string | null
  phone: string
  address: string
  city: string
  photoUrl: string | null
  averageRating: number
  totalReviews: number
  totalSales: number
  totalOrders: number
  isVerified: boolean
  isOpen: boolean
  operatingHours: string | null
  createdAt: Date
  updatedAt: Date
  _count: PenjualCountAggregateOutputType | null
  _avg: PenjualAvgAggregateOutputType | null
  _sum: PenjualSumAggregateOutputType | null
  _min: PenjualMinAggregateOutputType | null
  _max: PenjualMaxAggregateOutputType | null
}

export type GetPenjualGroupByPayload<T extends PenjualGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PenjualGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PenjualGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PenjualGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PenjualGroupByOutputType[P]>
      }
    >
  >



export type PenjualWhereInput = {
  AND?: Prisma.PenjualWhereInput | Prisma.PenjualWhereInput[]
  OR?: Prisma.PenjualWhereInput[]
  NOT?: Prisma.PenjualWhereInput | Prisma.PenjualWhereInput[]
  id?: Prisma.StringFilter<"Penjual"> | string
  userId?: Prisma.StringFilter<"Penjual"> | string
  businessName?: Prisma.StringFilter<"Penjual"> | string
  description?: Prisma.StringNullableFilter<"Penjual"> | string | null
  phone?: Prisma.StringFilter<"Penjual"> | string
  address?: Prisma.StringFilter<"Penjual"> | string
  city?: Prisma.StringFilter<"Penjual"> | string
  photoUrl?: Prisma.StringNullableFilter<"Penjual"> | string | null
  averageRating?: Prisma.FloatFilter<"Penjual"> | number
  totalReviews?: Prisma.IntFilter<"Penjual"> | number
  totalSales?: Prisma.FloatFilter<"Penjual"> | number
  totalOrders?: Prisma.IntFilter<"Penjual"> | number
  isVerified?: Prisma.BoolFilter<"Penjual"> | boolean
  isOpen?: Prisma.BoolFilter<"Penjual"> | boolean
  operatingHours?: Prisma.StringNullableFilter<"Penjual"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Penjual"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Penjual"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  menus?: Prisma.MenuListRelationFilter
  menuCategories?: Prisma.MenuCategoryListRelationFilter
  orders?: Prisma.OrderListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
  promotions?: Prisma.PromotionListRelationFilter
}

export type PenjualOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  isOpen?: Prisma.SortOrder
  operatingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  menus?: Prisma.MenuOrderByRelationAggregateInput
  menuCategories?: Prisma.MenuCategoryOrderByRelationAggregateInput
  orders?: Prisma.OrderOrderByRelationAggregateInput
  reviews?: Prisma.ReviewOrderByRelationAggregateInput
  promotions?: Prisma.PromotionOrderByRelationAggregateInput
  _relevance?: Prisma.PenjualOrderByRelevanceInput
}

export type PenjualWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  businessName?: string
  phone?: string
  AND?: Prisma.PenjualWhereInput | Prisma.PenjualWhereInput[]
  OR?: Prisma.PenjualWhereInput[]
  NOT?: Prisma.PenjualWhereInput | Prisma.PenjualWhereInput[]
  description?: Prisma.StringNullableFilter<"Penjual"> | string | null
  address?: Prisma.StringFilter<"Penjual"> | string
  city?: Prisma.StringFilter<"Penjual"> | string
  photoUrl?: Prisma.StringNullableFilter<"Penjual"> | string | null
  averageRating?: Prisma.FloatFilter<"Penjual"> | number
  totalReviews?: Prisma.IntFilter<"Penjual"> | number
  totalSales?: Prisma.FloatFilter<"Penjual"> | number
  totalOrders?: Prisma.IntFilter<"Penjual"> | number
  isVerified?: Prisma.BoolFilter<"Penjual"> | boolean
  isOpen?: Prisma.BoolFilter<"Penjual"> | boolean
  operatingHours?: Prisma.StringNullableFilter<"Penjual"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Penjual"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Penjual"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  menus?: Prisma.MenuListRelationFilter
  menuCategories?: Prisma.MenuCategoryListRelationFilter
  orders?: Prisma.OrderListRelationFilter
  reviews?: Prisma.ReviewListRelationFilter
  promotions?: Prisma.PromotionListRelationFilter
}, "id" | "userId" | "businessName" | "phone">

export type PenjualOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  isOpen?: Prisma.SortOrder
  operatingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PenjualCountOrderByAggregateInput
  _avg?: Prisma.PenjualAvgOrderByAggregateInput
  _max?: Prisma.PenjualMaxOrderByAggregateInput
  _min?: Prisma.PenjualMinOrderByAggregateInput
  _sum?: Prisma.PenjualSumOrderByAggregateInput
}

export type PenjualScalarWhereWithAggregatesInput = {
  AND?: Prisma.PenjualScalarWhereWithAggregatesInput | Prisma.PenjualScalarWhereWithAggregatesInput[]
  OR?: Prisma.PenjualScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PenjualScalarWhereWithAggregatesInput | Prisma.PenjualScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Penjual"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Penjual"> | string
  businessName?: Prisma.StringWithAggregatesFilter<"Penjual"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Penjual"> | string | null
  phone?: Prisma.StringWithAggregatesFilter<"Penjual"> | string
  address?: Prisma.StringWithAggregatesFilter<"Penjual"> | string
  city?: Prisma.StringWithAggregatesFilter<"Penjual"> | string
  photoUrl?: Prisma.StringNullableWithAggregatesFilter<"Penjual"> | string | null
  averageRating?: Prisma.FloatWithAggregatesFilter<"Penjual"> | number
  totalReviews?: Prisma.IntWithAggregatesFilter<"Penjual"> | number
  totalSales?: Prisma.FloatWithAggregatesFilter<"Penjual"> | number
  totalOrders?: Prisma.IntWithAggregatesFilter<"Penjual"> | number
  isVerified?: Prisma.BoolWithAggregatesFilter<"Penjual"> | boolean
  isOpen?: Prisma.BoolWithAggregatesFilter<"Penjual"> | boolean
  operatingHours?: Prisma.StringNullableWithAggregatesFilter<"Penjual"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Penjual"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Penjual"> | Date | string
}

export type PenjualCreateInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPenjualInput
  menus?: Prisma.MenuCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuUncheckedCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryUncheckedCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPenjualNestedInput
  menus?: Prisma.MenuUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUncheckedUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUncheckedUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPenjualNestedInput
}

export type PenjualCreateManyInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PenjualUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenjualUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PenjualNullableScalarRelationFilter = {
  is?: Prisma.PenjualWhereInput | null
  isNot?: Prisma.PenjualWhereInput | null
}

export type PenjualOrderByRelevanceInput = {
  fields: Prisma.PenjualOrderByRelevanceFieldEnum | Prisma.PenjualOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PenjualCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  isOpen?: Prisma.SortOrder
  operatingHours?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenjualAvgOrderByAggregateInput = {
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
}

export type PenjualMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  isOpen?: Prisma.SortOrder
  operatingHours?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenjualMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  businessName?: Prisma.SortOrder
  description?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  address?: Prisma.SortOrder
  city?: Prisma.SortOrder
  photoUrl?: Prisma.SortOrder
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
  isVerified?: Prisma.SortOrder
  isOpen?: Prisma.SortOrder
  operatingHours?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PenjualSumOrderByAggregateInput = {
  averageRating?: Prisma.SortOrder
  totalReviews?: Prisma.SortOrder
  totalSales?: Prisma.SortOrder
  totalOrders?: Prisma.SortOrder
}

export type PenjualScalarRelationFilter = {
  is?: Prisma.PenjualWhereInput
  isNot?: Prisma.PenjualWhereInput
}

export type PenjualCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutUserInput, Prisma.PenjualUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutUserInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutUserInput, Prisma.PenjualUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutUserInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutUserInput, Prisma.PenjualUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutUserInput
  upsert?: Prisma.PenjualUpsertWithoutUserInput
  disconnect?: Prisma.PenjualWhereInput | boolean
  delete?: Prisma.PenjualWhereInput | boolean
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutUserInput, Prisma.PenjualUpdateWithoutUserInput>, Prisma.PenjualUncheckedUpdateWithoutUserInput>
}

export type PenjualUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutUserInput, Prisma.PenjualUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutUserInput
  upsert?: Prisma.PenjualUpsertWithoutUserInput
  disconnect?: Prisma.PenjualWhereInput | boolean
  delete?: Prisma.PenjualWhereInput | boolean
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutUserInput, Prisma.PenjualUpdateWithoutUserInput>, Prisma.PenjualUncheckedUpdateWithoutUserInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type PenjualCreateNestedOneWithoutMenuCategoriesInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutMenuCategoriesInput, Prisma.PenjualUncheckedCreateWithoutMenuCategoriesInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutMenuCategoriesInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUpdateOneRequiredWithoutMenuCategoriesNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutMenuCategoriesInput, Prisma.PenjualUncheckedCreateWithoutMenuCategoriesInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutMenuCategoriesInput
  upsert?: Prisma.PenjualUpsertWithoutMenuCategoriesInput
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutMenuCategoriesInput, Prisma.PenjualUpdateWithoutMenuCategoriesInput>, Prisma.PenjualUncheckedUpdateWithoutMenuCategoriesInput>
}

export type PenjualCreateNestedOneWithoutMenusInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutMenusInput, Prisma.PenjualUncheckedCreateWithoutMenusInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutMenusInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUpdateOneRequiredWithoutMenusNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutMenusInput, Prisma.PenjualUncheckedCreateWithoutMenusInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutMenusInput
  upsert?: Prisma.PenjualUpsertWithoutMenusInput
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutMenusInput, Prisma.PenjualUpdateWithoutMenusInput>, Prisma.PenjualUncheckedUpdateWithoutMenusInput>
}

export type PenjualCreateNestedOneWithoutOrdersInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutOrdersInput, Prisma.PenjualUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutOrdersInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUpdateOneRequiredWithoutOrdersNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutOrdersInput, Prisma.PenjualUncheckedCreateWithoutOrdersInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutOrdersInput
  upsert?: Prisma.PenjualUpsertWithoutOrdersInput
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutOrdersInput, Prisma.PenjualUpdateWithoutOrdersInput>, Prisma.PenjualUncheckedUpdateWithoutOrdersInput>
}

export type PenjualCreateNestedOneWithoutReviewsInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutReviewsInput, Prisma.PenjualUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutReviewsInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUpdateOneRequiredWithoutReviewsNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutReviewsInput, Prisma.PenjualUncheckedCreateWithoutReviewsInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutReviewsInput
  upsert?: Prisma.PenjualUpsertWithoutReviewsInput
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutReviewsInput, Prisma.PenjualUpdateWithoutReviewsInput>, Prisma.PenjualUncheckedUpdateWithoutReviewsInput>
}

export type PenjualCreateNestedOneWithoutPromotionsInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutPromotionsInput, Prisma.PenjualUncheckedCreateWithoutPromotionsInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutPromotionsInput
  connect?: Prisma.PenjualWhereUniqueInput
}

export type PenjualUpdateOneRequiredWithoutPromotionsNestedInput = {
  create?: Prisma.XOR<Prisma.PenjualCreateWithoutPromotionsInput, Prisma.PenjualUncheckedCreateWithoutPromotionsInput>
  connectOrCreate?: Prisma.PenjualCreateOrConnectWithoutPromotionsInput
  upsert?: Prisma.PenjualUpsertWithoutPromotionsInput
  connect?: Prisma.PenjualWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PenjualUpdateToOneWithWhereWithoutPromotionsInput, Prisma.PenjualUpdateWithoutPromotionsInput>, Prisma.PenjualUncheckedUpdateWithoutPromotionsInput>
}

export type PenjualCreateWithoutUserInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateWithoutUserInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuUncheckedCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryUncheckedCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualCreateOrConnectWithoutUserInput = {
  where: Prisma.PenjualWhereUniqueInput
  create: Prisma.XOR<Prisma.PenjualCreateWithoutUserInput, Prisma.PenjualUncheckedCreateWithoutUserInput>
}

export type PenjualUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.PenjualUpdateWithoutUserInput, Prisma.PenjualUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PenjualCreateWithoutUserInput, Prisma.PenjualUncheckedCreateWithoutUserInput>
  where?: Prisma.PenjualWhereInput
}

export type PenjualUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.PenjualWhereInput
  data: Prisma.XOR<Prisma.PenjualUpdateWithoutUserInput, Prisma.PenjualUncheckedUpdateWithoutUserInput>
}

export type PenjualUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUncheckedUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUncheckedUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPenjualNestedInput
}

export type PenjualCreateWithoutMenuCategoriesInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPenjualInput
  menus?: Prisma.MenuCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateWithoutMenuCategoriesInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuUncheckedCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualCreateOrConnectWithoutMenuCategoriesInput = {
  where: Prisma.PenjualWhereUniqueInput
  create: Prisma.XOR<Prisma.PenjualCreateWithoutMenuCategoriesInput, Prisma.PenjualUncheckedCreateWithoutMenuCategoriesInput>
}

export type PenjualUpsertWithoutMenuCategoriesInput = {
  update: Prisma.XOR<Prisma.PenjualUpdateWithoutMenuCategoriesInput, Prisma.PenjualUncheckedUpdateWithoutMenuCategoriesInput>
  create: Prisma.XOR<Prisma.PenjualCreateWithoutMenuCategoriesInput, Prisma.PenjualUncheckedCreateWithoutMenuCategoriesInput>
  where?: Prisma.PenjualWhereInput
}

export type PenjualUpdateToOneWithWhereWithoutMenuCategoriesInput = {
  where?: Prisma.PenjualWhereInput
  data: Prisma.XOR<Prisma.PenjualUpdateWithoutMenuCategoriesInput, Prisma.PenjualUncheckedUpdateWithoutMenuCategoriesInput>
}

export type PenjualUpdateWithoutMenuCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPenjualNestedInput
  menus?: Prisma.MenuUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateWithoutMenuCategoriesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUncheckedUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPenjualNestedInput
}

export type PenjualCreateWithoutMenusInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateWithoutMenusInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menuCategories?: Prisma.MenuCategoryUncheckedCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualCreateOrConnectWithoutMenusInput = {
  where: Prisma.PenjualWhereUniqueInput
  create: Prisma.XOR<Prisma.PenjualCreateWithoutMenusInput, Prisma.PenjualUncheckedCreateWithoutMenusInput>
}

export type PenjualUpsertWithoutMenusInput = {
  update: Prisma.XOR<Prisma.PenjualUpdateWithoutMenusInput, Prisma.PenjualUncheckedUpdateWithoutMenusInput>
  create: Prisma.XOR<Prisma.PenjualCreateWithoutMenusInput, Prisma.PenjualUncheckedCreateWithoutMenusInput>
  where?: Prisma.PenjualWhereInput
}

export type PenjualUpdateToOneWithWhereWithoutMenusInput = {
  where?: Prisma.PenjualWhereInput
  data: Prisma.XOR<Prisma.PenjualUpdateWithoutMenusInput, Prisma.PenjualUncheckedUpdateWithoutMenusInput>
}

export type PenjualUpdateWithoutMenusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateWithoutMenusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menuCategories?: Prisma.MenuCategoryUncheckedUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPenjualNestedInput
}

export type PenjualCreateWithoutOrdersInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPenjualInput
  menus?: Prisma.MenuCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateWithoutOrdersInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuUncheckedCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryUncheckedCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualCreateOrConnectWithoutOrdersInput = {
  where: Prisma.PenjualWhereUniqueInput
  create: Prisma.XOR<Prisma.PenjualCreateWithoutOrdersInput, Prisma.PenjualUncheckedCreateWithoutOrdersInput>
}

export type PenjualUpsertWithoutOrdersInput = {
  update: Prisma.XOR<Prisma.PenjualUpdateWithoutOrdersInput, Prisma.PenjualUncheckedUpdateWithoutOrdersInput>
  create: Prisma.XOR<Prisma.PenjualCreateWithoutOrdersInput, Prisma.PenjualUncheckedCreateWithoutOrdersInput>
  where?: Prisma.PenjualWhereInput
}

export type PenjualUpdateToOneWithWhereWithoutOrdersInput = {
  where?: Prisma.PenjualWhereInput
  data: Prisma.XOR<Prisma.PenjualUpdateWithoutOrdersInput, Prisma.PenjualUncheckedUpdateWithoutOrdersInput>
}

export type PenjualUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPenjualNestedInput
  menus?: Prisma.MenuUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateWithoutOrdersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUncheckedUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUncheckedUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPenjualNestedInput
}

export type PenjualCreateWithoutReviewsInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPenjualInput
  menus?: Prisma.MenuCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateWithoutReviewsInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuUncheckedCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryUncheckedCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPenjualInput
  promotions?: Prisma.PromotionUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualCreateOrConnectWithoutReviewsInput = {
  where: Prisma.PenjualWhereUniqueInput
  create: Prisma.XOR<Prisma.PenjualCreateWithoutReviewsInput, Prisma.PenjualUncheckedCreateWithoutReviewsInput>
}

export type PenjualUpsertWithoutReviewsInput = {
  update: Prisma.XOR<Prisma.PenjualUpdateWithoutReviewsInput, Prisma.PenjualUncheckedUpdateWithoutReviewsInput>
  create: Prisma.XOR<Prisma.PenjualCreateWithoutReviewsInput, Prisma.PenjualUncheckedCreateWithoutReviewsInput>
  where?: Prisma.PenjualWhereInput
}

export type PenjualUpdateToOneWithWhereWithoutReviewsInput = {
  where?: Prisma.PenjualWhereInput
  data: Prisma.XOR<Prisma.PenjualUpdateWithoutReviewsInput, Prisma.PenjualUncheckedUpdateWithoutReviewsInput>
}

export type PenjualUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPenjualNestedInput
  menus?: Prisma.MenuUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateWithoutReviewsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUncheckedUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUncheckedUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPenjualNestedInput
  promotions?: Prisma.PromotionUncheckedUpdateManyWithoutPenjualNestedInput
}

export type PenjualCreateWithoutPromotionsInput = {
  id?: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutPenjualInput
  menus?: Prisma.MenuCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewCreateNestedManyWithoutPenjualInput
}

export type PenjualUncheckedCreateWithoutPromotionsInput = {
  id?: string
  userId: string
  businessName: string
  description?: string | null
  phone: string
  address: string
  city: string
  photoUrl?: string | null
  averageRating?: number
  totalReviews?: number
  totalSales?: number
  totalOrders?: number
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  menus?: Prisma.MenuUncheckedCreateNestedManyWithoutPenjualInput
  menuCategories?: Prisma.MenuCategoryUncheckedCreateNestedManyWithoutPenjualInput
  orders?: Prisma.OrderUncheckedCreateNestedManyWithoutPenjualInput
  reviews?: Prisma.ReviewUncheckedCreateNestedManyWithoutPenjualInput
}

export type PenjualCreateOrConnectWithoutPromotionsInput = {
  where: Prisma.PenjualWhereUniqueInput
  create: Prisma.XOR<Prisma.PenjualCreateWithoutPromotionsInput, Prisma.PenjualUncheckedCreateWithoutPromotionsInput>
}

export type PenjualUpsertWithoutPromotionsInput = {
  update: Prisma.XOR<Prisma.PenjualUpdateWithoutPromotionsInput, Prisma.PenjualUncheckedUpdateWithoutPromotionsInput>
  create: Prisma.XOR<Prisma.PenjualCreateWithoutPromotionsInput, Prisma.PenjualUncheckedCreateWithoutPromotionsInput>
  where?: Prisma.PenjualWhereInput
}

export type PenjualUpdateToOneWithWhereWithoutPromotionsInput = {
  where?: Prisma.PenjualWhereInput
  data: Prisma.XOR<Prisma.PenjualUpdateWithoutPromotionsInput, Prisma.PenjualUncheckedUpdateWithoutPromotionsInput>
}

export type PenjualUpdateWithoutPromotionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutPenjualNestedInput
  menus?: Prisma.MenuUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUpdateManyWithoutPenjualNestedInput
}

export type PenjualUncheckedUpdateWithoutPromotionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  businessName?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  photoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  averageRating?: Prisma.FloatFieldUpdateOperationsInput | number
  totalReviews?: Prisma.IntFieldUpdateOperationsInput | number
  totalSales?: Prisma.FloatFieldUpdateOperationsInput | number
  totalOrders?: Prisma.IntFieldUpdateOperationsInput | number
  isVerified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  operatingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menus?: Prisma.MenuUncheckedUpdateManyWithoutPenjualNestedInput
  menuCategories?: Prisma.MenuCategoryUncheckedUpdateManyWithoutPenjualNestedInput
  orders?: Prisma.OrderUncheckedUpdateManyWithoutPenjualNestedInput
  reviews?: Prisma.ReviewUncheckedUpdateManyWithoutPenjualNestedInput
}


/**
 * Count Type PenjualCountOutputType
 */

export type PenjualCountOutputType = {
  menus: number
  menuCategories: number
  orders: number
  reviews: number
  promotions: number
}

export type PenjualCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  menus?: boolean | PenjualCountOutputTypeCountMenusArgs
  menuCategories?: boolean | PenjualCountOutputTypeCountMenuCategoriesArgs
  orders?: boolean | PenjualCountOutputTypeCountOrdersArgs
  reviews?: boolean | PenjualCountOutputTypeCountReviewsArgs
  promotions?: boolean | PenjualCountOutputTypeCountPromotionsArgs
}

/**
 * PenjualCountOutputType without action
 */
export type PenjualCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PenjualCountOutputType
   */
  select?: Prisma.PenjualCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PenjualCountOutputType without action
 */
export type PenjualCountOutputTypeCountMenusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MenuWhereInput
}

/**
 * PenjualCountOutputType without action
 */
export type PenjualCountOutputTypeCountMenuCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MenuCategoryWhereInput
}

/**
 * PenjualCountOutputType without action
 */
export type PenjualCountOutputTypeCountOrdersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
}

/**
 * PenjualCountOutputType without action
 */
export type PenjualCountOutputTypeCountReviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReviewWhereInput
}

/**
 * PenjualCountOutputType without action
 */
export type PenjualCountOutputTypeCountPromotionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PromotionWhereInput
}


export type PenjualSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  businessName?: boolean
  description?: boolean
  phone?: boolean
  address?: boolean
  city?: boolean
  photoUrl?: boolean
  averageRating?: boolean
  totalReviews?: boolean
  totalSales?: boolean
  totalOrders?: boolean
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  menus?: boolean | Prisma.Penjual$menusArgs<ExtArgs>
  menuCategories?: boolean | Prisma.Penjual$menuCategoriesArgs<ExtArgs>
  orders?: boolean | Prisma.Penjual$ordersArgs<ExtArgs>
  reviews?: boolean | Prisma.Penjual$reviewsArgs<ExtArgs>
  promotions?: boolean | Prisma.Penjual$promotionsArgs<ExtArgs>
  _count?: boolean | Prisma.PenjualCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["penjual"]>



export type PenjualSelectScalar = {
  id?: boolean
  userId?: boolean
  businessName?: boolean
  description?: boolean
  phone?: boolean
  address?: boolean
  city?: boolean
  photoUrl?: boolean
  averageRating?: boolean
  totalReviews?: boolean
  totalSales?: boolean
  totalOrders?: boolean
  isVerified?: boolean
  isOpen?: boolean
  operatingHours?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PenjualOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "businessName" | "description" | "phone" | "address" | "city" | "photoUrl" | "averageRating" | "totalReviews" | "totalSales" | "totalOrders" | "isVerified" | "isOpen" | "operatingHours" | "createdAt" | "updatedAt", ExtArgs["result"]["penjual"]>
export type PenjualInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  menus?: boolean | Prisma.Penjual$menusArgs<ExtArgs>
  menuCategories?: boolean | Prisma.Penjual$menuCategoriesArgs<ExtArgs>
  orders?: boolean | Prisma.Penjual$ordersArgs<ExtArgs>
  reviews?: boolean | Prisma.Penjual$reviewsArgs<ExtArgs>
  promotions?: boolean | Prisma.Penjual$promotionsArgs<ExtArgs>
  _count?: boolean | Prisma.PenjualCountOutputTypeDefaultArgs<ExtArgs>
}

export type $PenjualPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Penjual"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    menus: Prisma.$MenuPayload<ExtArgs>[]
    menuCategories: Prisma.$MenuCategoryPayload<ExtArgs>[]
    orders: Prisma.$OrderPayload<ExtArgs>[]
    reviews: Prisma.$ReviewPayload<ExtArgs>[]
    promotions: Prisma.$PromotionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    businessName: string
    description: string | null
    phone: string
    address: string
    city: string
    photoUrl: string | null
    averageRating: number
    totalReviews: number
    totalSales: number
    totalOrders: number
    isVerified: boolean
    isOpen: boolean
    operatingHours: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["penjual"]>
  composites: {}
}

export type PenjualGetPayload<S extends boolean | null | undefined | PenjualDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PenjualPayload, S>

export type PenjualCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PenjualFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PenjualCountAggregateInputType | true
  }

export interface PenjualDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Penjual'], meta: { name: 'Penjual' } }
  /**
   * Find zero or one Penjual that matches the filter.
   * @param {PenjualFindUniqueArgs} args - Arguments to find a Penjual
   * @example
   * // Get one Penjual
   * const penjual = await prisma.penjual.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PenjualFindUniqueArgs>(args: Prisma.SelectSubset<T, PenjualFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Penjual that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PenjualFindUniqueOrThrowArgs} args - Arguments to find a Penjual
   * @example
   * // Get one Penjual
   * const penjual = await prisma.penjual.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PenjualFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PenjualFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Penjual that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualFindFirstArgs} args - Arguments to find a Penjual
   * @example
   * // Get one Penjual
   * const penjual = await prisma.penjual.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PenjualFindFirstArgs>(args?: Prisma.SelectSubset<T, PenjualFindFirstArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Penjual that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualFindFirstOrThrowArgs} args - Arguments to find a Penjual
   * @example
   * // Get one Penjual
   * const penjual = await prisma.penjual.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PenjualFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PenjualFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Penjuals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Penjuals
   * const penjuals = await prisma.penjual.findMany()
   * 
   * // Get first 10 Penjuals
   * const penjuals = await prisma.penjual.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const penjualWithIdOnly = await prisma.penjual.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PenjualFindManyArgs>(args?: Prisma.SelectSubset<T, PenjualFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Penjual.
   * @param {PenjualCreateArgs} args - Arguments to create a Penjual.
   * @example
   * // Create one Penjual
   * const Penjual = await prisma.penjual.create({
   *   data: {
   *     // ... data to create a Penjual
   *   }
   * })
   * 
   */
  create<T extends PenjualCreateArgs>(args: Prisma.SelectSubset<T, PenjualCreateArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Penjuals.
   * @param {PenjualCreateManyArgs} args - Arguments to create many Penjuals.
   * @example
   * // Create many Penjuals
   * const penjual = await prisma.penjual.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PenjualCreateManyArgs>(args?: Prisma.SelectSubset<T, PenjualCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Penjual.
   * @param {PenjualDeleteArgs} args - Arguments to delete one Penjual.
   * @example
   * // Delete one Penjual
   * const Penjual = await prisma.penjual.delete({
   *   where: {
   *     // ... filter to delete one Penjual
   *   }
   * })
   * 
   */
  delete<T extends PenjualDeleteArgs>(args: Prisma.SelectSubset<T, PenjualDeleteArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Penjual.
   * @param {PenjualUpdateArgs} args - Arguments to update one Penjual.
   * @example
   * // Update one Penjual
   * const penjual = await prisma.penjual.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PenjualUpdateArgs>(args: Prisma.SelectSubset<T, PenjualUpdateArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Penjuals.
   * @param {PenjualDeleteManyArgs} args - Arguments to filter Penjuals to delete.
   * @example
   * // Delete a few Penjuals
   * const { count } = await prisma.penjual.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PenjualDeleteManyArgs>(args?: Prisma.SelectSubset<T, PenjualDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Penjuals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Penjuals
   * const penjual = await prisma.penjual.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PenjualUpdateManyArgs>(args: Prisma.SelectSubset<T, PenjualUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Penjual.
   * @param {PenjualUpsertArgs} args - Arguments to update or create a Penjual.
   * @example
   * // Update or create a Penjual
   * const penjual = await prisma.penjual.upsert({
   *   create: {
   *     // ... data to create a Penjual
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Penjual we want to update
   *   }
   * })
   */
  upsert<T extends PenjualUpsertArgs>(args: Prisma.SelectSubset<T, PenjualUpsertArgs<ExtArgs>>): Prisma.Prisma__PenjualClient<runtime.Types.Result.GetResult<Prisma.$PenjualPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Penjuals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualCountArgs} args - Arguments to filter Penjuals to count.
   * @example
   * // Count the number of Penjuals
   * const count = await prisma.penjual.count({
   *   where: {
   *     // ... the filter for the Penjuals we want to count
   *   }
   * })
  **/
  count<T extends PenjualCountArgs>(
    args?: Prisma.Subset<T, PenjualCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PenjualCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Penjual.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PenjualAggregateArgs>(args: Prisma.Subset<T, PenjualAggregateArgs>): Prisma.PrismaPromise<GetPenjualAggregateType<T>>

  /**
   * Group by Penjual.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PenjualGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PenjualGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PenjualGroupByArgs['orderBy'] }
      : { orderBy?: PenjualGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PenjualGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPenjualGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Penjual model
 */
readonly fields: PenjualFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Penjual.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PenjualClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  menus<T extends Prisma.Penjual$menusArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penjual$menusArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  menuCategories<T extends Prisma.Penjual$menuCategoriesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penjual$menuCategoriesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuCategoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orders<T extends Prisma.Penjual$ordersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penjual$ordersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  reviews<T extends Prisma.Penjual$reviewsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penjual$reviewsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReviewPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  promotions<T extends Prisma.Penjual$promotionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Penjual$promotionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PromotionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Penjual model
 */
export interface PenjualFieldRefs {
  readonly id: Prisma.FieldRef<"Penjual", 'String'>
  readonly userId: Prisma.FieldRef<"Penjual", 'String'>
  readonly businessName: Prisma.FieldRef<"Penjual", 'String'>
  readonly description: Prisma.FieldRef<"Penjual", 'String'>
  readonly phone: Prisma.FieldRef<"Penjual", 'String'>
  readonly address: Prisma.FieldRef<"Penjual", 'String'>
  readonly city: Prisma.FieldRef<"Penjual", 'String'>
  readonly photoUrl: Prisma.FieldRef<"Penjual", 'String'>
  readonly averageRating: Prisma.FieldRef<"Penjual", 'Float'>
  readonly totalReviews: Prisma.FieldRef<"Penjual", 'Int'>
  readonly totalSales: Prisma.FieldRef<"Penjual", 'Float'>
  readonly totalOrders: Prisma.FieldRef<"Penjual", 'Int'>
  readonly isVerified: Prisma.FieldRef<"Penjual", 'Boolean'>
  readonly isOpen: Prisma.FieldRef<"Penjual", 'Boolean'>
  readonly operatingHours: Prisma.FieldRef<"Penjual", 'String'>
  readonly createdAt: Prisma.FieldRef<"Penjual", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Penjual", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Penjual findUnique
 */
export type PenjualFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * Filter, which Penjual to fetch.
   */
  where: Prisma.PenjualWhereUniqueInput
}

/**
 * Penjual findUniqueOrThrow
 */
export type PenjualFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * Filter, which Penjual to fetch.
   */
  where: Prisma.PenjualWhereUniqueInput
}

/**
 * Penjual findFirst
 */
export type PenjualFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * Filter, which Penjual to fetch.
   */
  where?: Prisma.PenjualWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penjuals to fetch.
   */
  orderBy?: Prisma.PenjualOrderByWithRelationInput | Prisma.PenjualOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Penjuals.
   */
  cursor?: Prisma.PenjualWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penjuals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penjuals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Penjuals.
   */
  distinct?: Prisma.PenjualScalarFieldEnum | Prisma.PenjualScalarFieldEnum[]
}

/**
 * Penjual findFirstOrThrow
 */
export type PenjualFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * Filter, which Penjual to fetch.
   */
  where?: Prisma.PenjualWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penjuals to fetch.
   */
  orderBy?: Prisma.PenjualOrderByWithRelationInput | Prisma.PenjualOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Penjuals.
   */
  cursor?: Prisma.PenjualWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penjuals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penjuals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Penjuals.
   */
  distinct?: Prisma.PenjualScalarFieldEnum | Prisma.PenjualScalarFieldEnum[]
}

/**
 * Penjual findMany
 */
export type PenjualFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * Filter, which Penjuals to fetch.
   */
  where?: Prisma.PenjualWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Penjuals to fetch.
   */
  orderBy?: Prisma.PenjualOrderByWithRelationInput | Prisma.PenjualOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Penjuals.
   */
  cursor?: Prisma.PenjualWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Penjuals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Penjuals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Penjuals.
   */
  distinct?: Prisma.PenjualScalarFieldEnum | Prisma.PenjualScalarFieldEnum[]
}

/**
 * Penjual create
 */
export type PenjualCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * The data needed to create a Penjual.
   */
  data: Prisma.XOR<Prisma.PenjualCreateInput, Prisma.PenjualUncheckedCreateInput>
}

/**
 * Penjual createMany
 */
export type PenjualCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Penjuals.
   */
  data: Prisma.PenjualCreateManyInput | Prisma.PenjualCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Penjual update
 */
export type PenjualUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * The data needed to update a Penjual.
   */
  data: Prisma.XOR<Prisma.PenjualUpdateInput, Prisma.PenjualUncheckedUpdateInput>
  /**
   * Choose, which Penjual to update.
   */
  where: Prisma.PenjualWhereUniqueInput
}

/**
 * Penjual updateMany
 */
export type PenjualUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Penjuals.
   */
  data: Prisma.XOR<Prisma.PenjualUpdateManyMutationInput, Prisma.PenjualUncheckedUpdateManyInput>
  /**
   * Filter which Penjuals to update
   */
  where?: Prisma.PenjualWhereInput
  /**
   * Limit how many Penjuals to update.
   */
  limit?: number
}

/**
 * Penjual upsert
 */
export type PenjualUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * The filter to search for the Penjual to update in case it exists.
   */
  where: Prisma.PenjualWhereUniqueInput
  /**
   * In case the Penjual found by the `where` argument doesn't exist, create a new Penjual with this data.
   */
  create: Prisma.XOR<Prisma.PenjualCreateInput, Prisma.PenjualUncheckedCreateInput>
  /**
   * In case the Penjual was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PenjualUpdateInput, Prisma.PenjualUncheckedUpdateInput>
}

/**
 * Penjual delete
 */
export type PenjualDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
  /**
   * Filter which Penjual to delete.
   */
  where: Prisma.PenjualWhereUniqueInput
}

/**
 * Penjual deleteMany
 */
export type PenjualDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Penjuals to delete
   */
  where?: Prisma.PenjualWhereInput
  /**
   * Limit how many Penjuals to delete.
   */
  limit?: number
}

/**
 * Penjual.menus
 */
export type Penjual$menusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Menu
   */
  select?: Prisma.MenuSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Menu
   */
  omit?: Prisma.MenuOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuInclude<ExtArgs> | null
  where?: Prisma.MenuWhereInput
  orderBy?: Prisma.MenuOrderByWithRelationInput | Prisma.MenuOrderByWithRelationInput[]
  cursor?: Prisma.MenuWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MenuScalarFieldEnum | Prisma.MenuScalarFieldEnum[]
}

/**
 * Penjual.menuCategories
 */
export type Penjual$menuCategoriesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuCategory
   */
  select?: Prisma.MenuCategorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuCategory
   */
  omit?: Prisma.MenuCategoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuCategoryInclude<ExtArgs> | null
  where?: Prisma.MenuCategoryWhereInput
  orderBy?: Prisma.MenuCategoryOrderByWithRelationInput | Prisma.MenuCategoryOrderByWithRelationInput[]
  cursor?: Prisma.MenuCategoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MenuCategoryScalarFieldEnum | Prisma.MenuCategoryScalarFieldEnum[]
}

/**
 * Penjual.orders
 */
export type Penjual$ordersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  cursor?: Prisma.OrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Penjual.reviews
 */
export type Penjual$reviewsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Review
   */
  select?: Prisma.ReviewSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Review
   */
  omit?: Prisma.ReviewOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ReviewInclude<ExtArgs> | null
  where?: Prisma.ReviewWhereInput
  orderBy?: Prisma.ReviewOrderByWithRelationInput | Prisma.ReviewOrderByWithRelationInput[]
  cursor?: Prisma.ReviewWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ReviewScalarFieldEnum | Prisma.ReviewScalarFieldEnum[]
}

/**
 * Penjual.promotions
 */
export type Penjual$promotionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Promotion
   */
  select?: Prisma.PromotionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Promotion
   */
  omit?: Prisma.PromotionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PromotionInclude<ExtArgs> | null
  where?: Prisma.PromotionWhereInput
  orderBy?: Prisma.PromotionOrderByWithRelationInput | Prisma.PromotionOrderByWithRelationInput[]
  cursor?: Prisma.PromotionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PromotionScalarFieldEnum | Prisma.PromotionScalarFieldEnum[]
}

/**
 * Penjual without action
 */
export type PenjualDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Penjual
   */
  select?: Prisma.PenjualSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Penjual
   */
  omit?: Prisma.PenjualOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PenjualInclude<ExtArgs> | null
}
