
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Pembeli: 'Pembeli',
  Penjual: 'Penjual',
  Admin: 'Admin',
  Category: 'Category',
  MenuCategory: 'MenuCategory',
  Menu: 'Menu',
  CartItem: 'CartItem',
  FavoriteMenu: 'FavoriteMenu',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Payment: 'Payment',
  Review: 'Review',
  Promotion: 'Promotion',
  PromotionItem: 'PromotionItem',
  Address: 'Address'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const PembeliScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  phone: 'phone',
  address: 'address',
  city: 'city',
  photoUrl: 'photoUrl',
  totalSpent: 'totalSpent',
  totalOrders: 'totalOrders',
  averageRating: 'averageRating',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PembeliScalarFieldEnum = (typeof PembeliScalarFieldEnum)[keyof typeof PembeliScalarFieldEnum]


export const PenjualScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  businessName: 'businessName',
  description: 'description',
  phone: 'phone',
  address: 'address',
  city: 'city',
  photoUrl: 'photoUrl',
  averageRating: 'averageRating',
  totalReviews: 'totalReviews',
  totalSales: 'totalSales',
  totalOrders: 'totalOrders',
  isVerified: 'isVerified',
  isOpen: 'isOpen',
  operatingHours: 'operatingHours',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PenjualScalarFieldEnum = (typeof PenjualScalarFieldEnum)[keyof typeof PenjualScalarFieldEnum]


export const AdminScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  department: 'department',
  permissions: 'permissions',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AdminScalarFieldEnum = (typeof AdminScalarFieldEnum)[keyof typeof AdminScalarFieldEnum]


export const CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  icon: 'icon',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CategoryScalarFieldEnum = (typeof CategoryScalarFieldEnum)[keyof typeof CategoryScalarFieldEnum]


export const MenuCategoryScalarFieldEnum = {
  id: 'id',
  penjualId: 'penjualId',
  name: 'name',
  description: 'description',
  icon: 'icon',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MenuCategoryScalarFieldEnum = (typeof MenuCategoryScalarFieldEnum)[keyof typeof MenuCategoryScalarFieldEnum]


export const MenuScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  menuCategoryId: 'menuCategoryId',
  penjualId: 'penjualId',
  stock: 'stock',
  cost: 'cost',
  image: 'image',
  averageRating: 'averageRating',
  totalReviews: 'totalReviews',
  isAvailable: 'isAvailable',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MenuScalarFieldEnum = (typeof MenuScalarFieldEnum)[keyof typeof MenuScalarFieldEnum]


export const CartItemScalarFieldEnum = {
  id: 'id',
  pembeliId: 'pembeliId',
  menuId: 'menuId',
  quantity: 'quantity',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CartItemScalarFieldEnum = (typeof CartItemScalarFieldEnum)[keyof typeof CartItemScalarFieldEnum]


export const FavoriteMenuScalarFieldEnum = {
  id: 'id',
  pembeliId: 'pembeliId',
  menuId: 'menuId',
  createdAt: 'createdAt'
} as const

export type FavoriteMenuScalarFieldEnum = (typeof FavoriteMenuScalarFieldEnum)[keyof typeof FavoriteMenuScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  transactionCode: 'transactionCode',
  pembeliId: 'pembeliId',
  penjualId: 'penjualId',
  status: 'status',
  deliveryType: 'deliveryType',
  subtotal: 'subtotal',
  tax: 'tax',
  discountAmount: 'discountAmount',
  shippingCost: 'shippingCost',
  totalPrice: 'totalPrice',
  paymentMethod: 'paymentMethod',
  paymentStatus: 'paymentStatus',
  deliveryAddress: 'deliveryAddress',
  estimatedTime: 'estimatedTime',
  completedAt: 'completedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  menuId: 'menuId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  subtotal: 'subtotal',
  createdAt: 'createdAt'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  method: 'method',
  amount: 'amount',
  status: 'status',
  proofUrl: 'proofUrl',
  transactionId: 'transactionId',
  snapToken: 'snapToken',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const ReviewScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  menuId: 'menuId',
  pembeliId: 'pembeliId',
  penjualId: 'penjualId',
  rating: 'rating',
  comment: 'comment',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ReviewScalarFieldEnum = (typeof ReviewScalarFieldEnum)[keyof typeof ReviewScalarFieldEnum]


export const PromotionScalarFieldEnum = {
  id: 'id',
  penjualId: 'penjualId',
  title: 'title',
  description: 'description',
  discountType: 'discountType',
  discountValue: 'discountValue',
  maxDiscount: 'maxDiscount',
  startDate: 'startDate',
  endDate: 'endDate',
  isActive: 'isActive',
  minPurchase: 'minPurchase',
  maxUses: 'maxUses',
  usedCount: 'usedCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PromotionScalarFieldEnum = (typeof PromotionScalarFieldEnum)[keyof typeof PromotionScalarFieldEnum]


export const PromotionItemScalarFieldEnum = {
  id: 'id',
  promotionId: 'promotionId',
  menuId: 'menuId'
} as const

export type PromotionItemScalarFieldEnum = (typeof PromotionItemScalarFieldEnum)[keyof typeof PromotionItemScalarFieldEnum]


export const AddressScalarFieldEnum = {
  id: 'id',
  pembeliId: 'pembeliId',
  label: 'label',
  address: 'address',
  city: 'city',
  zipCode: 'zipCode',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type AddressScalarFieldEnum = (typeof AddressScalarFieldEnum)[keyof typeof AddressScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  password: 'password'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const PembeliOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  phone: 'phone',
  address: 'address',
  city: 'city',
  photoUrl: 'photoUrl'
} as const

export type PembeliOrderByRelevanceFieldEnum = (typeof PembeliOrderByRelevanceFieldEnum)[keyof typeof PembeliOrderByRelevanceFieldEnum]


export const PenjualOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  businessName: 'businessName',
  description: 'description',
  phone: 'phone',
  address: 'address',
  city: 'city',
  photoUrl: 'photoUrl',
  operatingHours: 'operatingHours'
} as const

export type PenjualOrderByRelevanceFieldEnum = (typeof PenjualOrderByRelevanceFieldEnum)[keyof typeof PenjualOrderByRelevanceFieldEnum]


export const AdminOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  fullName: 'fullName',
  department: 'department',
  permissions: 'permissions'
} as const

export type AdminOrderByRelevanceFieldEnum = (typeof AdminOrderByRelevanceFieldEnum)[keyof typeof AdminOrderByRelevanceFieldEnum]


export const CategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  icon: 'icon'
} as const

export type CategoryOrderByRelevanceFieldEnum = (typeof CategoryOrderByRelevanceFieldEnum)[keyof typeof CategoryOrderByRelevanceFieldEnum]


export const MenuCategoryOrderByRelevanceFieldEnum = {
  id: 'id',
  penjualId: 'penjualId',
  name: 'name',
  description: 'description',
  icon: 'icon'
} as const

export type MenuCategoryOrderByRelevanceFieldEnum = (typeof MenuCategoryOrderByRelevanceFieldEnum)[keyof typeof MenuCategoryOrderByRelevanceFieldEnum]


export const MenuOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  menuCategoryId: 'menuCategoryId',
  penjualId: 'penjualId',
  image: 'image'
} as const

export type MenuOrderByRelevanceFieldEnum = (typeof MenuOrderByRelevanceFieldEnum)[keyof typeof MenuOrderByRelevanceFieldEnum]


export const CartItemOrderByRelevanceFieldEnum = {
  id: 'id',
  pembeliId: 'pembeliId',
  menuId: 'menuId'
} as const

export type CartItemOrderByRelevanceFieldEnum = (typeof CartItemOrderByRelevanceFieldEnum)[keyof typeof CartItemOrderByRelevanceFieldEnum]


export const FavoriteMenuOrderByRelevanceFieldEnum = {
  id: 'id',
  pembeliId: 'pembeliId',
  menuId: 'menuId'
} as const

export type FavoriteMenuOrderByRelevanceFieldEnum = (typeof FavoriteMenuOrderByRelevanceFieldEnum)[keyof typeof FavoriteMenuOrderByRelevanceFieldEnum]


export const OrderOrderByRelevanceFieldEnum = {
  id: 'id',
  transactionCode: 'transactionCode',
  pembeliId: 'pembeliId',
  penjualId: 'penjualId',
  deliveryAddress: 'deliveryAddress',
  notes: 'notes'
} as const

export type OrderOrderByRelevanceFieldEnum = (typeof OrderOrderByRelevanceFieldEnum)[keyof typeof OrderOrderByRelevanceFieldEnum]


export const OrderItemOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  menuId: 'menuId'
} as const

export type OrderItemOrderByRelevanceFieldEnum = (typeof OrderItemOrderByRelevanceFieldEnum)[keyof typeof OrderItemOrderByRelevanceFieldEnum]


export const PaymentOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  proofUrl: 'proofUrl',
  transactionId: 'transactionId',
  snapToken: 'snapToken'
} as const

export type PaymentOrderByRelevanceFieldEnum = (typeof PaymentOrderByRelevanceFieldEnum)[keyof typeof PaymentOrderByRelevanceFieldEnum]


export const ReviewOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  menuId: 'menuId',
  pembeliId: 'pembeliId',
  penjualId: 'penjualId',
  comment: 'comment'
} as const

export type ReviewOrderByRelevanceFieldEnum = (typeof ReviewOrderByRelevanceFieldEnum)[keyof typeof ReviewOrderByRelevanceFieldEnum]


export const PromotionOrderByRelevanceFieldEnum = {
  id: 'id',
  penjualId: 'penjualId',
  title: 'title',
  description: 'description',
  discountType: 'discountType'
} as const

export type PromotionOrderByRelevanceFieldEnum = (typeof PromotionOrderByRelevanceFieldEnum)[keyof typeof PromotionOrderByRelevanceFieldEnum]


export const PromotionItemOrderByRelevanceFieldEnum = {
  id: 'id',
  promotionId: 'promotionId',
  menuId: 'menuId'
} as const

export type PromotionItemOrderByRelevanceFieldEnum = (typeof PromotionItemOrderByRelevanceFieldEnum)[keyof typeof PromotionItemOrderByRelevanceFieldEnum]


export const AddressOrderByRelevanceFieldEnum = {
  id: 'id',
  pembeliId: 'pembeliId',
  label: 'label',
  address: 'address',
  city: 'city',
  zipCode: 'zipCode'
} as const

export type AddressOrderByRelevanceFieldEnum = (typeof AddressOrderByRelevanceFieldEnum)[keyof typeof AddressOrderByRelevanceFieldEnum]

