
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Pembeli
 * 
 */
export type Pembeli = Prisma.PembeliModel
/**
 * Model Penjual
 * 
 */
export type Penjual = Prisma.PenjualModel
/**
 * Model Admin
 * 
 */
export type Admin = Prisma.AdminModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model MenuCategory
 * 
 */
export type MenuCategory = Prisma.MenuCategoryModel
/**
 * Model Menu
 * 
 */
export type Menu = Prisma.MenuModel
/**
 * Model CartItem
 * 
 */
export type CartItem = Prisma.CartItemModel
/**
 * Model FavoriteMenu
 * 
 */
export type FavoriteMenu = Prisma.FavoriteMenuModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Review
 * 
 */
export type Review = Prisma.ReviewModel
/**
 * Model Promotion
 * 
 */
export type Promotion = Prisma.PromotionModel
/**
 * Model PromotionItem
 * 
 */
export type PromotionItem = Prisma.PromotionItemModel
/**
 * Model Address
 * 
 */
export type Address = Prisma.AddressModel
